<a href="https://colab.research.google.com/github/Atha1407/MediRent-Ai/blob/main/notebooks/01_Data_Preprocessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
from google.colab import files

uploaded = files.upload()

Saving newlife_medical_equipment_ai_dataset.xlsx to newlife_medical_equipment_ai_dataset.xlsx

In [6]:
import pandas as pd

df = pd.read_excel("newlife_medical_equipment_ai_dataset.xlsx")

print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

df.head()

Rows: 3520
Columns: 32

,Rental_ID,Rental_Date,Customer_ID,Customer_Type,Area,Equipment,Equipment_Category,Rental_Duration_Days,Daily_Rate,Total_Rental_Amount,...,Booking_Status,Cancellation_Status,Customer_Pincode,Equipment_ID,Acquisition_Date,Maintenance_Date,Next_Maintenance_Due,Equipment_Age_Years,Total_Inventory,Available_Units_At_Start
0,REN0001,2026-02-17,CUST155,Individual Patient,Wanowrie,Oxygen Concentrator,Respiratory Equipment,21,260,5460,...,Completed,Not Cancelled,411038.0,OC-005,2024-02-15,2026-06-16,2026-10-14,2.5,16,12
1,REN0002,2026-07-18,CUST169,Diagnostic Center,Shivajinagar,Surgical Headlight,Surgical Equipment,7,170,1190,...,Completed,Not Cancelled,411052.0,SH-006,2025-01-03,2025-04-27,2025-07-26,1.6,8,4
2,REN0003,2026-06-18,CUST391,Hospital,Wakad,Oxygen Concentrator,Respiratory Equipment,3,300,900,...,Completed,Not Cancelled,411007.0,OC-003,2024-12-09,2025-07-09,2026-07-09,1.6,16,8
3,REN0004,2026-04-01,CUST350,Diagnostic Center,Hinjawadi,BiPAP Machine,Respiratory Equipment,14,560,7840,...,Completed,Not Cancelled,411042.0,BP-006,2023-06-13,2023-11-02,2024-04-30,3.1,11,6
4,REN0005,2026-06-26,CUST357,Home Care,Baner,Ventilator,Critical Care Equipment,21,1140,23940,...,Completed,Not Cancelled,411015.0,VT-004,2023-09-08,2024-10-14,2025-04-12,2.9,8,7

In [7]:
print("Column Names and Data Types:\n")

print(df.dtypes)

Column Names and Data Types:

Rental_ID                    object
Rental_Date                  object
Customer_ID                  object
Customer_Type                object
Area                         object
Equipment                    object
Equipment_Category           object
Rental_Duration_Days          int64
Daily_Rate                    int64
Total_Rental_Amount           int64
Security_Deposit              int64
Delivery_Charge               int64
Maintenance_Cost              int64
Payment_Mode                 object
Rental_Status                object
Equipment_Condition          object
Customer_Rating             float64
Return_Date                  object
Booking_Date                 object
Rental_Start_Date            object
Expected_Return_Date         object
Actual_Return_Date           object
Booking_Status               object
Cancellation_Status          object
Customer_Pincode            float64
Equipment_ID                 object
Acquisition_Date             object
Maintenance_Date             object
Next_Maintenance_Due         object
Equipment_Age_Years         float64
Total_Inventory               int64
Available_Units_At_Start      int64
dtype: object

In [8]:
print("Missing Values:")
print(df.isnull().sum())

Missing Values:
Rental_ID                     0
Rental_Date                   0
Customer_ID                   0
Customer_Type                 0
Area                          0
Equipment                     0
Equipment_Category            0
Rental_Duration_Days          0
Daily_Rate                    0
Total_Rental_Amount           0
Security_Deposit              0
Delivery_Charge               0
Maintenance_Cost              0
Payment_Mode                  0
Rental_Status                 0
Equipment_Condition           0
Customer_Rating             247
Return_Date                 492
Booking_Date                  0
Rental_Start_Date             0
Expected_Return_Date        173
Actual_Return_Date          492
Booking_Status                0
Cancellation_Status           0
Customer_Pincode            122
Equipment_ID                146
Acquisition_Date            146
Maintenance_Date            247
Next_Maintenance_Due        246
Equipment_Age_Years         146
Total_Inventory               0
Available_Units_At_Start      0
dtype: int64

In [9]:
print(df["Rental_Status"].value_counts())

print("\nBooking Status:")
print(df["Booking_Status"].value_counts())

print("\nCancellation Status:")
print(df["Cancellation_Status"].value_counts())

Rental_Status
Returned     3005
Active        346
Cancelled     144
returned       23
Canceled        2
Name: count, dtype: int64

Booking Status:
Booking_Status
Completed    3028
Confirmed     346
Cancelled     146
Name: count, dtype: int64

Cancellation Status:
Cancellation_Status
Not Cancelled    3374
Cancelled         146
Name: count, dtype: int64

In [10]:
print(df[df["Actual_Return_Date"].isnull()]["Rental_Status"].value_counts())

print("\nBooking Status:")
print(df[df["Actual_Return_Date"].isnull()]["Booking_Status"].value_counts())

print("\nCancellation Status:")
print(df[df["Actual_Return_Date"].isnull()]["Cancellation_Status"].value_counts())

Rental_Status
Active       346
Cancelled    144
Canceled       2
Name: count, dtype: int64

Booking Status:
Booking_Status
Confirmed    346
Cancelled    146
Name: count, dtype: int64

Cancellation Status:
Cancellation_Status
Not Cancelled    346
Cancelled        146
Name: count, dtype: int64

In [11]:
print(df[df["Return_Date"].isnull()]["Rental_Status"].value_counts())

print("\nBooking Status:")
print(df[df["Return_Date"].isnull()]["Booking_Status"].value_counts())

print("\nCancellation Status:")
print(df[df["Return_Date"].isnull()]["Cancellation_Status"].value_counts())

Rental_Status
Active       346
Cancelled    144
Canceled       2
Name: count, dtype: int64

Booking Status:
Booking_Status
Confirmed    346
Cancelled    146
Name: count, dtype: int64

Cancellation Status:
Cancellation_Status
Not Cancelled    346
Cancelled        146
Name: count, dtype: int64

In [12]:
print("Duplicate rows:", df.duplicated().sum())

Duplicate rows: 19

In [13]:
duplicates = df[df.duplicated(keep=False)]

print("Total duplicate rows:", len(duplicates))

duplicates

Total duplicate rows: 38

,Rental_ID,Rental_Date,Customer_ID,Customer_Type,Area,Equipment,Equipment_Category,Rental_Duration_Days,Daily_Rate,Total_Rental_Amount,...,Booking_Status,Cancellation_Status,Customer_Pincode,Equipment_ID,Acquisition_Date,Maintenance_Date,Next_Maintenance_Due,Equipment_Age_Years,Total_Inventory,Available_Units_At_Start
309,REN0310,2026-02-01,CUST136,Home Care,Hinjawadi,CPAP Machine,Respiratory Equipment,10,330,3300,...,Completed,Not Cancelled,411014.0,CP-013,2024-04-10,2026-03-03,2027-03-03,2.3,19,16
325,REN0326,2026-03-02,CUST345,Individual Patient,Chinchwad,Hospital Bed,Patient Care Equipment,21,390,8190,...,Completed,Not Cancelled,411028.0,HB-023,2023-09-05,2024-01-10,2024-05-09,2.9,23,12
705,REN0706,2026-07-11,CUST164,Hospital,Wakad,Infusion Pump,Critical Care Equipment,30,340,10200,...,Completed,Not Cancelled,411038.0,IP-008,2023-06-01,2023-09-22,2024-01-20,3.2,10,6
751,REN0752,2024-01-08,CUST375,Home Care,Hinjawadi,BiPAP Machine,Respiratory Equipment,30,550,16500,...,Completed,Not Cancelled,411038.0,BP-003,2022-01-03,2023-01-31,2024-01-31,4.6,11,9
1187,REN1188,2024-07-30,CUST122,Individual Patient,Dhankawadi,Surgical Headlight,Surgical Equipment,14,200,2800,...,Completed,Not Cancelled,411030.0,SH-006,2025-01-03,2025-04-27,2025-07-26,1.6,8,8
1414,REN1415,2026-01-15,CUST473,Individual Patient,Chinchwad,Surgical Headlight,Surgical Equipment,7,190,1330,...,Completed,Not Cancelled,411009.0,SH-005,2023-10-28,2025-09-07,2025-12-06,2.8,8,8
1444,REN1445,2025-04-30,CUST273,Individual Patient,Pimpri,Wheelchair,Mobility Equipment,14,140,1960,...,Completed,Not Cancelled,411015.0,WC-007,2024-08-29,2026-04-11,2026-07-10,1.9,20,16
1647,REN1648,2026-03-20,CUST349,Individual Patient,Erandwane,ECG Machine,Diagnostic Equipment,7,510,3570,...,Completed,Not Cancelled,411058.0,ECG-005,2022-01-24,2022-08-13,2022-12-11,4.5,9,8
1650,REN1651,2025-05-21,CUST215,Hospital,Vishrantwadi,Oxygen Concentrator,Respiratory Equipment,14,300,4200,...,Completed,Not Cancelled,411007.0,OC-004,2025-03-27,2026-06-20,2026-12-17,1.3,16,12
1666,REN1667,2026-06-22,CUST206,Individual Patient,Shivajinagar,Wheelchair,Mobility Equipment,5,140,700,...,Completed,Not Cancelled,411043.0,WC-016,2024-07-04,2025-08-17,2025-12-15,2.1,20,10
1681,REN1682,2026-02-15,CUST040,Individual Patient,Aundh,Suction Machine,Surgical Equipment,7,230,1610,...,Completed,Not Cancelled,411007.0,SM-005,2023-02-15,2024-02-13,2025-02-12,3.5,14,7
1945,REN1946,2024-09-02,CUST305,Home Care,Koregaon Park,Commode Chair,Mobility Equipment,14,90,1260,...,Completed,Not Cancelled,411046.0,CC-005,2024-07-20,2024-10-24,2025-04-22,2.0,10,9
2232,REN2233,2025-06-07,CUST415,Hospital,Koregaon Park,CPAP Machine,Respiratory Equipment,21,380,7980,...,Completed,Not Cancelled,411052.0,CP-014,2024-05-28,2026-03-24,2027-03-24,2.2,19,17
2341,REN2342,2024-04-07,CUST273,Individual Patient,Baner,Oxygen Concentrator,Respiratory Equipment,14,260,3640,...,Cancelled,Cancelled,411027.0,NaN,NaN,NaN,NaN,NaN,16,16
2434,REN2435,2026-04-04,CUST024,Home Care,Kothrud,Hospital Bed,Patient Care Equipment,14,380,5320,...,Completed,Not Cancelled,411045.0,HB-019,2022-04-24,2024-04-14,2025-04-14,4.3,23,5
2456,REN2457,2024-05-17,CUST393,Individual Patient,Hinjawadi,Wheelchair,Mobility Equipment,14,160,2240,...,Completed,Not Cancelled,411057.0,WC-010,2022-10-28,2026-07-19,2027-01-15,3.8,20,13
2653,REN2654,2026-07-07,CUST345,Home Care,Baner,Patient Monitor,Monitoring Equipment,30,640,19200,...,Completed,Not Cancelled,411030.0,PM-007,2023-09-28,2024-02-25,2024-05-25,2.8,13,8
2820,REN2821,2024-09-11,CUST118,Home Care,Viman Nagar,Nebulizer,Respiratory Equipment,21,90,1890,...,Completed,Not Cancelled,411052.0,NB-008,2022-12-18,2025-07-25,2026-07-25,3.6,12,12
3043,REN3044,2024-09-24,CUST248,Individual Patient,Koregaon Park,Wheelchair,Mobility Equipment,7,160,1120,...,Completed,Not Cancelled,411038.0,WC-020,2023-01-10,2024-02-15,2024-06-14,3.6,20,15
3500,REN1651,2025-05-21,CUST215,Hospital,Vishrantwadi,Oxygen Concentrator,Respiratory Equipment,14,300,4200,...,Completed,Not Cancelled,411007.0,OC-004,2025-03-27,2026-06-20,2026-12-17,1.3,16,12
3501,REN2457,2024-05-17,CUST393,Individual Patient,Hinjawadi,Wheelchair,Mobility Equipment,14,160,2240,...,Completed,Not Cancelled,411057.0,WC-010,2022-10-28,2026-07-19,2027-01-15,3.8,20,13
3502,REN2233,2025-06-07,CUST415,Hospital,Koregaon Park,CPAP Machine,Respiratory Equipment,21,380,7980,...,Completed,Not Cancelled,411052.0,CP-014,2024-05-28,2026-03-24,2027-03-24,2.2,19,17
3503,REN1946,2024-09-02,CUST305,Home Care,Koregaon Park,Commode Chair,Mobility Equipment,14,90,1260,...,Completed,Not Cancelled,411046.0,CC-005,2024-07-20,2024-10-24,2025-04-22,2.0,10,9
3504,REN0310,2026-02-01,CUST136,Home Care,Hinjawadi,CPAP Machine,Respiratory Equipment,10,330,3300,...,Completed,Not Cancelled,411014.0,CP-013,2024-04-10,2026-03-03,2027-03-03,2.3,19,16
3505,REN2342,2024-04-07,CUST273,Individual Patient,Baner,Oxygen Concentrator,Respiratory Equipment,14,260,3640,...,Cancelled,Cancelled,411027.0,NaN,NaN,NaN,NaN,NaN,16,16
3506,REN1667,2026-06-22,CUST206,Individual Patient,Shivajinagar,Wheelchair,Mobility Equipment,5,140,700,...,Completed,Not Cancelled,411043.0,WC-016,2024-07-04,2025-08-17,2025-12-15,2.1,20,10
3507,REN1682,2026-02-15,CUST040,Individual Patient,Aundh,Suction Machine,Surgical Equipment,7,230,1610,...,Completed,Not Cancelled,411007.0,SM-005,2023-02-15,2024-02-13,2025-02-12,3.5,14,7
3508,REN1188,2024-07-30,CUST122,Individual Patient,Dhankawadi,Surgical Headlight,Surgical Equipment,14,200,2800,...,Completed,Not Cancelled,411030.0,SH-006,2025-01-03,2025-04-27,2025-07-26,1.6,8,8
3509,REN0326,2026-03-02,CUST345,Individual Patient,Chinchwad,Hospital Bed,Patient Care Equipment,21,390,8190,...,Completed,Not Cancelled,411028.0,HB-023,2023-09-05,2024-01-10,2024-05-09,2.9,23,12
3510,REN1648,2026-03-20,CUST349,Individual Patient,Erandwane,ECG Machine,Diagnostic Equipment,7,510,3570,...,Completed,Not Cancelled,411058.0,ECG-005,2022-01-24,2022-08-13,2022-12-11,4.5,9,8
3511,REN2821,2024-09-11,CUST118,Home Care,Viman Nagar,Nebulizer,Respiratory Equipment,21,90,1890,...,Completed,Not Cancelled,411052.0,NB-008,2022-12-18,2025-07-25,2026-07-25,3.6,12,12
3512,REN0752,2024-01-08,CUST375,Home Care,Hinjawadi,BiPAP Machine,Respiratory Equipment,30,550,16500,...,Completed,Not Cancelled,411038.0,BP-003,2022-01-03,2023-01-31,2024-01-31,4.6,11,9
3513,REN1415,2026-01-15,CUST473,Individual Patient,Chinchwad,Surgical Headlight,Surgical Equipment,7,190,1330,...,Completed,Not Cancelled,411009.0,SH-005,2023-10-28,2025-09-07,2025-12-06,2.8,8,8
3514,REN2435,2026-04-04,CUST024,Home Care,Kothrud,Hospital Bed,Patient Care Equipment,14,380,5320,...,Completed,Not Cancelled,411045.0,HB-019,2022-04-24,2024-04-14,2025-04-14,4.3,23,5
3515,REN0706,2026-07-11,CUST164,Hospital,Wakad,Infusion Pump,Critical Care Equipment,30,340,10200,...,Completed,Not Cancelled,411038.0,IP-008,2023-06-01,2023-09-22,2024-01-20,3.2,10,6
3516,REN3044,2024-09-24,CUST248,Individual Patient,Koregaon Park,Wheelchair,Mobility Equipment,7,160,1120,...,Completed,Not Cancelled,411038.0,WC-020,2023-01-10,2024-02-15,2024-06-14,3.6,20,15
3517,REN2654,2026-07-07,CUST345,Home Care,Baner,Patient Monitor,Monitoring Equipment,30,640,19200,...,Completed,Not Cancelled,411030.0,PM-007,2023-09-28,2024-02-25,2024-05-25,2.8,13,8
3519,REN1445,2025-04-30,CUST273,Individual Patient,Pimpri,Wheelchair,Mobility Equipment,14,140,1960,...,Completed,Not Cancelled,411015.0,WC-007,2024-08-29,2026-04-11,2026-07-10,1.9,20,16

In [14]:
print("Duplicate Rental IDs:", df["Rental_ID"].duplicated().sum())

Duplicate Rental IDs: 20

In [15]:
print(df["Rental_ID"].nunique())

3500

In [16]:
duplicate_ids = df[df["Rental_ID"].duplicated(keep=False)]

print("Rows with repeated Rental IDs:", len(duplicate_ids))

duplicate_ids[["Rental_ID", "Rental_Date", "Customer_ID", "Equipment",
               "Rental_Status", "Total_Rental_Amount"]].sort_values("Rental_ID")

Rows with repeated Rental IDs: 40

,Rental_ID,Rental_Date,Customer_ID,Equipment,Rental_Status,Total_Rental_Amount
309,REN0310,2026-02-01,CUST136,CPAP Machine,Returned,3300
3504,REN0310,2026-02-01,CUST136,CPAP Machine,Returned,3300
325,REN0326,2026-03-02,CUST345,Hospital Bed,Returned,8190
3509,REN0326,2026-03-02,CUST345,Hospital Bed,Returned,8190
705,REN0706,2026-07-11,CUST164,Infusion Pump,Returned,10200
3515,REN0706,2026-07-11,CUST164,Infusion Pump,Returned,10200
751,REN0752,2024-01-08,CUST375,BiPAP Machine,Returned,16500
3512,REN0752,2024-01-08,CUST375,BiPAP Machine,Returned,16500
1187,REN1188,2024-07-30,CUST122,Surgical Headlight,Returned,2800
3508,REN1188,2024-07-30,CUST122,Surgical Headlight,Returned,2800
1414,REN1415,2026-01-15,CUST473,Surgical Headlight,Returned,1330
3513,REN1415,2026-01-15,CUST473,Surgical Headlight,Returned,1330
3519,REN1445,2025-04-30,CUST273,Wheelchair,Returned,1960
1444,REN1445,2025-04-30,CUST273,Wheelchair,Returned,1960
1647,REN1648,2026-03-20,CUST349,ECG Machine,Returned,3570
3510,REN1648,2026-03-20,CUST349,ECG Machine,Returned,3570
1650,REN1651,2025-05-21,CUST215,Oxygen Concentrator,Returned,4200
3500,REN1651,2025-05-21,CUST215,Oxygen Concentrator,Returned,4200
3506,REN1667,2026-06-22,CUST206,Wheelchair,Returned,700
1666,REN1667,2026-06-22,CUST206,Wheelchair,Returned,700
1681,REN1682,2026-02-15,CUST040,Suction Machine,Returned,1610
3507,REN1682,2026-02-15,CUST040,Suction Machine,Returned,1610
3503,REN1946,2024-09-02,CUST305,Commode Chair,Returned,1260
1945,REN1946,2024-09-02,CUST305,Commode Chair,Returned,1260
3502,REN2233,2025-06-07,CUST415,CPAP Machine,Returned,7980
2232,REN2233,2025-06-07,CUST415,CPAP Machine,Returned,7980
2341,REN2342,2024-04-07,CUST273,Oxygen Concentrator,Cancelled,3640
3505,REN2342,2024-04-07,CUST273,Oxygen Concentrator,Cancelled,3640
3514,REN2435,2026-04-04,CUST024,Hospital Bed,Returned,5320
2434,REN2435,2026-04-04,CUST024,Hospital Bed,Returned,5320
3501,REN2457,2024-05-17,CUST393,Wheelchair,Returned,2240
2456,REN2457,2024-05-17,CUST393,Wheelchair,Returned,2240
2653,REN2654,2026-07-07,CUST345,Patient Monitor,Returned,19200
3517,REN2654,2026-07-07,CUST345,Patient Monitor,Returned,19200
2820,REN2821,2024-09-11,CUST118,Nebulizer,Returned,1890
3511,REN2821,2024-09-11,CUST118,Nebulizer,Returned,1890
3043,REN3044,2024-09-24,CUST248,Wheelchair,Returned,1120
3516,REN3044,2024-09-24,CUST248,Wheelchair,Returned,1120
3518,REN3360,2024-07-30,CUST521,Wheelchair,Returned,910
3359,REN3360,30-Jul-2024,CUST521,Wheelchair,Returned,910

In [17]:
df[df["Rental_ID"] == "REN3360"].T

                                        3359                3518
Rental_ID                            REN3360             REN3360
Rental_Date                      30-Jul-2024          2024-07-30
Customer_ID                          CUST521             CUST521
Customer_Type                      Home Care           Home Care
Area                               Erandwane           Erandwane
Equipment                         Wheelchair          Wheelchair
Equipment_Category        Mobility Equipment  Mobility Equipment
Rental_Duration_Days                       7                   7
Daily_Rate                               130                 130
Total_Rental_Amount                      910                 910
Security_Deposit                        1820                1820
Delivery_Charge                          600                 600
Maintenance_Cost                          16                  16
Payment_Mode                   Bank Transfer       Bank Transfer
Rental_Status                       Returned            Returned
Equipment_Condition                     Good                Good
Customer_Rating                          4.0                 4.0
Return_Date                       2024-08-06          2024-08-06
Booking_Date                      2024-07-29          2024-07-29
Rental_Start_Date                 2024-07-30          2024-07-30
Expected_Return_Date              2024-08-06          2024-08-06
Actual_Return_Date                2024-08-06          2024-08-06
Booking_Status                     Completed           Completed
Cancellation_Status            Not Cancelled       Not Cancelled
Customer_Pincode                    411058.0            411058.0
Equipment_ID                          WC-012              WC-012
Acquisition_Date                  2025-04-29          2025-04-29
Maintenance_Date                  2026-05-02          2026-05-02
Next_Maintenance_Due              2027-05-02          2027-05-02
Equipment_Age_Years                      1.3                 1.3
Total_Inventory                           20                  20
Available_Units_At_Start                  18                  18

In [18]:
df = df.drop_duplicates()

print("Rows after removing duplicates:", df.shape[0])
print("Columns:", df.shape[1])

Rows after removing duplicates: 3501
Columns: 32

In [19]:
print("Duplicate Rental IDs remaining:",
      df["Rental_ID"].duplicated().sum())

print("\nRepeated Rental IDs:")

print(
    df[df["Rental_ID"].duplicated(keep=False)]["Rental_ID"]
    .value_counts()
)

Duplicate Rental IDs remaining: 1

Repeated Rental IDs:
Rental_ID
REN3360    2
Name: count, dtype: int64

In [20]:
date_columns = [
    "Rental_Date",
    "Return_Date",
    "Booking_Date",
    "Rental_Start_Date",
    "Expected_Return_Date",
    "Actual_Return_Date",
    "Acquisition_Date",
    "Maintenance_Date",
    "Next_Maintenance_Due"
]

for col in date_columns:
    print(f"\n{col}")
    print(df[col].dropna().head(5).to_list())

Rental_Date
['2026-02-17', '2026-07-18', '2026-06-18', '2026-04-01', '2026-06-26']

Return_Date
['2026-03-10', '2026-07-25', '2026-06-21', '2026-04-15', '2026-07-17']

Booking_Date
['2026-02-06', '2026-07-15', '2026-06-14', '2026-03-23', '2026-06-23']

Rental_Start_Date
['2026-02-17', '2026-07-18', '2026-06-18', '2026-04-01', '2026-06-26']

Expected_Return_Date
['2026-03-10', '2026-07-25', '2026-06-21', '2026-04-15', '2026-07-17']

Actual_Return_Date
['2026-03-10', '2026-07-25', '2026-06-21', '2026-04-15', '2026-07-17']

Acquisition_Date
['2024-02-15', '2025-01-03', '2024-12-09', '2023-06-13', '2023-09-08']

Maintenance_Date
['2026-06-16', '2025-04-27', '2025-07-09', '2023-11-02', '2024-10-14']

Next_Maintenance_Due
['2026-10-14', '2025-07-26', '2026-07-09', '2024-04-30', '2025-04-12']

In [21]:
for col in date_columns:
    df[col] = pd.to_datetime(df[col], errors="coerce")

print(df[date_columns].dtypes)

Rental_Date             datetime64[ns]
Return_Date             datetime64[ns]
Booking_Date            datetime64[ns]
Rental_Start_Date       datetime64[ns]
Expected_Return_Date    datetime64[ns]
Actual_Return_Date      datetime64[ns]
Acquisition_Date        datetime64[ns]
Maintenance_Date        datetime64[ns]
Next_Maintenance_Due    datetime64[ns]
dtype: object

In [22]:
print("Duplicate rows:", df.duplicated().sum())

print("Duplicate Rental IDs:", df["Rental_ID"].duplicated().sum())

print("\nRepeated Rental IDs:")
print(
    df[df["Rental_ID"].duplicated(keep=False)]["Rental_ID"]
    .value_counts()
)

Duplicate rows: 0
Duplicate Rental IDs: 1

Repeated Rental IDs:
Rental_ID
REN3360    2
Name: count, dtype: int64

In [23]:
r = df[df["Rental_ID"] == "REN3360"]

print("Differences between the two REN3360 records:")

for col in df.columns:
    if r.iloc[0][col] != r.iloc[1][col]:
        print(
            f"{col}: "
            f"{r.iloc[0][col]}  <-->  {r.iloc[1][col]}"
        )

Differences between the two REN3360 records:
Rental_Date: NaT  <-->  2024-07-30 00:00:00

In [24]:
print("Missing Rental_Date values:", df["Rental_Date"].isna().sum())

Missing Rental_Date values: 35

In [25]:
df_raw = pd.read_excel("newlife_medical_equipment_ai_dataset.xlsx")

print("Original rows:", df_raw.shape[0])
print("Original Rental_Date missing:", df_raw["Rental_Date"].isna().sum())

Original rows: 3520
Original Rental_Date missing: 0

In [26]:
print(
    df_raw.loc[
        pd.to_datetime(df_raw["Rental_Date"], errors="coerce").isna(),
        "Rental_Date"
    ].unique()
)

['24-Feb-2026' '28-Feb-2026' '22-Apr-2026' '02/06/2026' '10/06/2025'
 '07-Jun-2026' '06/26/2025' '21/04/2025' '06/28/2024' '10-Jan-2024'
 '06-Aug-2025' '19/03/2024' '06/10/2025' '07/11/2025' '14/01/2025'
 '23/10/2024' '22/01/2026' '19-Apr-2026' '10/05/2025' '08/23/2025'
 '02/13/2024' '01/15/2024' '28-Jan-2025' '07/07/2025' '10-Dec-2025'
 '06/04/2026' '22/12/2025' '11-Nov-2025' '28/05/2025' '08/07/2024'
 '05/26/2026' '19-Apr-2025' '30-Jul-2024']

In [27]:
print(df_raw["Rental_Date"].astype(str).value_counts().head(50))

Rental_Date
2026-03-29    15
2026-07-31    14
2026-05-07    14
2026-02-20    13
2026-04-11    13
2026-06-01    13
2026-03-15    12
2026-07-07    12
2024-05-29    12
2026-03-05    12
2026-02-01    12
2026-02-17    12
2026-07-26    12
2026-04-24    11
2026-07-16    11
2026-04-04    11
2026-07-24    11
2026-03-20    11
2026-06-22    11
2026-03-06    11
2026-04-29    10
2026-06-10    10
2026-03-17    10
2026-06-27    10
2026-07-27    10
2026-07-04    10
2026-05-15    10
2026-02-26    10
2026-02-24    10
2026-02-11    10
2026-05-30    10
2026-05-28    10
2026-05-24    10
2026-03-21    10
2026-06-26     9
2026-04-01     9
2026-06-04     9
2026-05-20     9
2026-07-20     9
2026-07-23     9
2026-05-02     9
2026-05-04     9
2026-07-18     9
2026-06-18     9
2026-07-05     9
2026-04-03     9
2026-04-18     9
2026-02-05     9
2025-05-21     9
2025-09-04     9
Name: count, dtype: int64

In [28]:
print("\nSample Rental Dates:")
print(df_raw["Rental_Date"].sample(20, random_state=42).to_list())

Sample Rental Dates:
['2026-05-08', '2026-02-05', '2026-05-29', '2026-03-02', '2024-09-02', '2026-07-25', '2024-10-23', '2026-06-02', '2026-02-21', '2025-08-21', '2026-02-20', '2026-06-05', '2025-09-28', '2026-06-06', '2024-07-21', '2024-05-30', '2026-02-03', '2024-10-09', '2026-06-22', '2026-03-30']

In [29]:
mixed_dates = [
    "24-Feb-2026", "28-Feb-2026", "22-Apr-2026",
    "02/06/2026", "10/06/2025", "07-Jun-2026",
    "06/26/2025", "21/04/2025", "06/28/2024",
    "10-Jan-2024", "06-Aug-2025", "19/03/2024",
    "06/10/2025", "07/11/2025", "14/01/2025",
    "23/10/2024", "22/01/2026", "19-Apr-2026",
    "10/05/2025", "08/23/2025", "02/13/2024",
    "01/15/2024", "28-Jan-2025", "07/07/2025",
    "10-Dec-2025", "06/04/2026", "22/12/2025",
    "11-Nov-2025", "28/05/2025", "08/07/2024",
    "05/26/2026", "19-Apr-2025", "30-Jul-2024"
]

print(df_raw[df_raw["Rental_Date"].isin(mixed_dates)][
    ["Rental_ID", "Rental_Date", "Booking_Date", "Rental_Start_Date"]
].to_string(index=False))

Rental_ID Rental_Date Booking_Date Rental_Start_Date
  REN0109 24-Feb-2026   2026-02-13        2026-02-24
  REN0328 28-Feb-2026   2026-02-23        2026-02-28
  REN0601 22-Apr-2026   2026-04-10        2026-04-22
  REN0660  02/06/2026   2026-01-31        2026-02-06
  REN0854  10/06/2025   2025-06-09        2025-06-10
  REN0874 07-Jun-2026   2026-05-28        2026-06-07
  REN0985  06/26/2025   2025-06-21        2025-06-26
  REN1281  21/04/2025   2025-04-19        2025-04-21
  REN1363  06/28/2024   2024-06-26        2024-06-28
  REN1466 10-Jan-2024   2024-01-04        2024-01-10
  REN1470 06-Aug-2025   2025-08-01        2025-08-06
  REN1494  19/03/2024   2024-03-16        2024-03-19
  REN1532  06/10/2025   2025-06-05        2025-06-10
  REN1575  07/11/2025   2025-10-25        2025-11-07
  REN1770  14/01/2025   2025-01-08        2025-01-14
  REN1836  23/10/2024   2024-10-13        2024-10-23
  REN2051  22/01/2026   2026-01-15        2026-01-22
  REN2223 19-Apr-2026   2026-04-12        2026-04-19
  REN2488  10/05/2025   2025-09-26        2025-10-05
  REN2565  08/23/2025   2025-08-19        2025-08-23
  REN2658  19/03/2024   2024-03-11        2024-03-19
  REN2746  02/13/2024   2024-02-07        2024-02-13
  REN2815  01/15/2024   2024-01-05        2024-01-15
  REN2859 28-Jan-2025   2025-01-27        2025-01-28
  REN2860  02/13/2024   2024-02-07        2024-02-13
  REN2888  07/07/2025   2025-06-30        2025-07-07
  REN2967 10-Dec-2025   2025-12-05        2025-12-10
  REN2975  06/04/2026   2026-04-05        2026-04-06
  REN2988  22/12/2025   2025-12-19        2025-12-22
  REN3045 11-Nov-2025   2025-11-01        2025-11-11
  REN3144  28/05/2025   2025-05-25        2025-05-28
  REN3182  08/07/2024   2024-08-05        2024-08-07
  REN3194  05/26/2026   2026-05-21        2026-05-26
  REN3332 19-Apr-2025   2025-04-12        2025-04-19
  REN3360 30-Jul-2024   2024-07-29        2024-07-30

In [30]:
test_rental_dates = pd.to_datetime(
    df_raw["Rental_Date"],
    format="mixed",
    dayfirst=False,
    errors="coerce"
)

print("Original missing:", df_raw["Rental_Date"].isna().sum())
print("Failed conversions:", test_rental_dates.isna().sum())

Original missing: 0
Failed conversions: 0

In [31]:
rental_dates = pd.to_datetime(
    df_raw["Rental_Date"],
    format="mixed",
    dayfirst=False,
    errors="coerce"
)

start_dates = pd.to_datetime(
    df_raw["Rental_Start_Date"],
    format="mixed",
    dayfirst=False,
    errors="coerce"
)

print("Rental dates:", rental_dates.notna().sum())
print("Start dates:", start_dates.notna().sum())

print("Dates that do not match:",
      (rental_dates != start_dates).sum())

Rental dates: 3520
Start dates: 3520
Dates that do not match: 3

In [32]:
comparison = pd.DataFrame({
    "Rental_ID": df_raw["Rental_ID"],
    "Rental_Date": df_raw["Rental_Date"],
    "Parsed_Rental_Date": rental_dates,
    "Rental_Start_Date": df_raw["Rental_Start_Date"],
    "Parsed_Start_Date": start_dates
})

mismatches = comparison[rental_dates != start_dates]

print(mismatches.to_string(index=False))

Rental_ID Rental_Date Parsed_Rental_Date Rental_Start_Date Parsed_Start_Date
  REN0854  10/06/2025         2025-10-06        2025-06-10        2025-06-10
  REN1575  07/11/2025         2025-07-11        2025-11-07        2025-11-07
  REN2975  06/04/2026         2026-06-04        2026-04-06        2026-04-06

In [33]:
print(
    "Rental_Date and Rental_Start_Date match:",
    (rental_dates == start_dates).sum(),
    "out of",
    len(df_raw)
)

Rental_Date and Rental_Start_Date match: 3517 out of 3520

In [34]:
# Start again from the untouched original dataset
df = df_raw.copy()

# Parse Rental_Date
df["Rental_Date"] = pd.to_datetime(
    df["Rental_Date"],
    format="mixed",
    dayfirst=False,
    errors="coerce"
)

# Parse Rental_Start_Date
df["Rental_Start_Date"] = pd.to_datetime(
    df["Rental_Start_Date"],
    format="mixed",
    dayfirst=False,
    errors="coerce"
)

# Use Rental_Start_Date to correct the 3 ambiguous Rental_Date values
df.loc[
    df["Rental_Date"] != df["Rental_Start_Date"],
    "Rental_Date"
] = df.loc[
    df["Rental_Date"] != df["Rental_Start_Date"],
    "Rental_Start_Date"
]

print("Rental_Date missing:", df["Rental_Date"].isna().sum())
print("Rental_Date mismatches:",
      (df["Rental_Date"] != df["Rental_Start_Date"]).sum())

Rental_Date missing: 0
Rental_Date mismatches: 0

In [35]:
remaining_date_columns = [
    "Return_Date",
    "Booking_Date",
    "Rental_Start_Date",
    "Expected_Return_Date",
    "Actual_Return_Date",
    "Acquisition_Date",
    "Maintenance_Date",
    "Next_Maintenance_Due"
]

for col in remaining_date_columns:
    parsed = pd.to_datetime(
        df_raw[col],
        format="mixed",
        dayfirst=False,
        errors="coerce"
    )

    original_missing = df_raw[col].isna().sum()
    parsed_missing = parsed.isna().sum()

    print(
        f"{col}: "
        f"Original missing = {original_missing}, "
        f"After parsing = {parsed_missing}"
    )

Return_Date: Original missing = 492, After parsing = 492
Booking_Date: Original missing = 0, After parsing = 0
Rental_Start_Date: Original missing = 0, After parsing = 0
Expected_Return_Date: Original missing = 173, After parsing = 173
Actual_Return_Date: Original missing = 492, After parsing = 492
Acquisition_Date: Original missing = 146, After parsing = 146
Maintenance_Date: Original missing = 247, After parsing = 247
Next_Maintenance_Due: Original missing = 246, After parsing = 246

In [36]:
date_columns = [
    "Rental_Date",
    "Return_Date",
    "Booking_Date",
    "Rental_Start_Date",
    "Expected_Return_Date",
    "Actual_Return_Date",
    "Acquisition_Date",
    "Maintenance_Date",
    "Next_Maintenance_Due"
]

for col in date_columns:
    df[col] = pd.to_datetime(
        df[col],
        format="mixed",
        dayfirst=False,
        errors="coerce"
    )

print(df[date_columns].dtypes)

Rental_Date             datetime64[ns]
Return_Date             datetime64[ns]
Booking_Date            datetime64[ns]
Rental_Start_Date       datetime64[ns]
Expected_Return_Date    datetime64[ns]
Actual_Return_Date      datetime64[ns]
Acquisition_Date        datetime64[ns]
Maintenance_Date        datetime64[ns]
Next_Maintenance_Due    datetime64[ns]
dtype: object

In [37]:
missing_report = pd.DataFrame({
    "Missing_Count": df.isna().sum(),
    "Missing_Percentage": (df.isna().sum() / len(df) * 100).round(2)
})

missing_report = missing_report[missing_report["Missing_Count"] > 0]

print(missing_report)

                      Missing_Count  Missing_Percentage
Customer_Rating                 247                7.02
Return_Date                     492               13.98
Expected_Return_Date            173                4.91
Actual_Return_Date              492               13.98
Customer_Pincode                122                3.47
Equipment_ID                    146                4.15
Acquisition_Date                146                4.15
Maintenance_Date                247                7.02
Next_Maintenance_Due            246                6.99
Equipment_Age_Years             146                4.15

In [38]:
print(df[df["Customer_Rating"].isna()]["Rental_Status"].value_counts())

Rental_Status
Returned     141
Active        76
Cancelled     30
Name: count, dtype: int64

In [39]:
print(df[df["Customer_Rating"].isna()]["Booking_Status"].value_counts())

Booking_Status
Completed    141
Confirmed     76
Cancelled     30
Name: count, dtype: int64

In [40]:
print(df[df["Expected_Return_Date"].isna()]["Rental_Status"].value_counts())

Rental_Status
Cancelled    144
Active        27
Canceled       2
Name: count, dtype: int64

In [41]:
print(df[df["Expected_Return_Date"].isna()]["Booking_Status"].value_counts())

Booking_Status
Cancelled    146
Confirmed     27
Name: count, dtype: int64

In [42]:
active_missing_expected = df[
    (df["Expected_Return_Date"].isna()) &
    (df["Rental_Status"] == "Active")
]

print(
    active_missing_expected[
        [
            "Rental_ID",
            "Rental_Date",
            "Rental_Duration_Days",
            "Rental_Status",
            "Booking_Status",
            "Cancellation_Status",
            "Actual_Return_Date"
        ]
    ].to_string(index=False)
)

Rental_ID Rental_Date  Rental_Duration_Days Rental_Status Booking_Status Cancellation_Status Actual_Return_Date
  REN0068  2026-06-10                     3        Active      Confirmed       Not Cancelled                NaT
  REN0156  2026-03-05                    10        Active      Confirmed       Not Cancelled                NaT
  REN0209  2026-05-06                     3        Active      Confirmed       Not Cancelled                NaT
  REN0316  2026-03-06                     3        Active      Confirmed       Not Cancelled                NaT
  REN0393  2026-03-09                    30        Active      Confirmed       Not Cancelled                NaT
  REN0681  2026-05-20                     7        Active      Confirmed       Not Cancelled                NaT
  REN0715  2025-02-27                    14        Active      Confirmed       Not Cancelled                NaT
  REN1148  2025-07-30                     3        Active      Confirmed       Not Cancelled                NaT
  REN1185  2024-02-06                    10        Active      Confirmed       Not Cancelled                NaT
  REN1910  2025-02-02                    45        Active      Confirmed       Not Cancelled                NaT
  REN2162  2025-05-29                     7        Active      Confirmed       Not Cancelled                NaT
  REN2173  2024-04-16                    10        Active      Confirmed       Not Cancelled                NaT
  REN2359  2025-01-13                     5        Active      Confirmed       Not Cancelled                NaT
  REN2703  2026-06-22                    10        Active      Confirmed       Not Cancelled                NaT
  REN2711  2024-02-18                    14        Active      Confirmed       Not Cancelled                NaT
  REN2724  2024-08-19                    30        Active      Confirmed       Not Cancelled                NaT
  REN2801  2025-12-05                    45        Active      Confirmed       Not Cancelled                NaT
  REN2877  2025-01-27                    30        Active      Confirmed       Not Cancelled                NaT
  REN2895  2025-07-18                     5        Active      Confirmed       Not Cancelled                NaT
  REN2937  2024-05-13                     3        Active      Confirmed       Not Cancelled                NaT
  REN2941  2024-10-02                    14        Active      Confirmed       Not Cancelled                NaT
  REN3177  2024-05-19                    10        Active      Confirmed       Not Cancelled                NaT
  REN3209  2025-05-22                    10        Active      Confirmed       Not Cancelled                NaT
  REN3211  2025-03-18                     7        Active      Confirmed       Not Cancelled                NaT
  REN3264  2025-05-08                     5        Active      Confirmed       Not Cancelled                NaT
  REN3340  2024-07-07                     7        Active      Confirmed       Not Cancelled                NaT
  REN3434  2024-11-08                    10        Active      Confirmed       Not Cancelled                NaT

In [43]:
calculated_expected = (
    df["Rental_Start_Date"] +
    pd.to_timedelta(df["Rental_Duration_Days"], unit="D")
)

check = df["Expected_Return_Date"].notna()

mismatches = (
    check &
    (df["Expected_Return_Date"] != calculated_expected)
)

print("Existing expected dates:", check.sum())
print("Mismatches:", mismatches.sum())

Existing expected dates: 3347
Mismatches: 5

In [44]:
mismatch_data = df.loc[
    mismatches,
    [
        "Rental_ID",
        "Rental_Start_Date",
        "Rental_Duration_Days",
        "Expected_Return_Date"
    ]
].copy()

mismatch_data["Calculated_Expected_Return"] = (
    mismatch_data["Rental_Start_Date"] +
    pd.to_timedelta(
        mismatch_data["Rental_Duration_Days"],
        unit="D"
    )
)

print(mismatch_data.to_string(index=False))

Rental_ID Rental_Start_Date  Rental_Duration_Days Expected_Return_Date Calculated_Expected_Return
  REN0217        2026-05-08                    60           2026-06-07                 2026-07-07
  REN2203        2024-12-15                    42           2025-01-05                 2025-01-26
  REN2387        2025-04-25                    20           2025-05-05                 2025-05-15
  REN2402        2026-07-18                     6           2026-07-21                 2026-07-24
  REN2788        2024-11-23                    20           2024-12-03                 2024-12-13

In [45]:
expected_duration = (
    df["Expected_Return_Date"] - df["Rental_Start_Date"]
).dt.days

print(expected_duration.describe())

count    3347.000000
mean       12.950105
std        10.483652
min         1.000000
25%         5.000000
50%        10.000000
75%        21.000000
max        45.000000
dtype: float64

In [46]:
comparison_duration = pd.DataFrame({
    "Rental_Duration_Days": df["Rental_Duration_Days"],
    "Expected_Duration_Days": expected_duration
})

print(comparison_duration.describe())

       Rental_Duration_Days  Expected_Duration_Days
count           3520.000000             3347.000000
mean              12.942330               12.950105
std               10.499669               10.483652
min                1.000000                1.000000
25%                5.000000                5.000000
50%               10.000000               10.000000
75%               21.000000               21.000000
max               60.000000               45.000000

In [47]:
active_missing = df[
    (df["Expected_Return_Date"].isna()) &
    (df["Rental_Status"] == "Active")
]

print(
    active_missing[
        ["Rental_ID", "Rental_Duration_Days"]
    ].to_string(index=False)
)

print("\nDuration statistics:")
print(active_missing["Rental_Duration_Days"].describe())

Rental_ID  Rental_Duration_Days
  REN0068                     3
  REN0156                    10
  REN0209                     3
  REN0316                     3
  REN0393                    30
  REN0681                     7
  REN0715                    14
  REN1148                     3
  REN1185                    10
  REN1910                    45
  REN2162                     7
  REN2173                    10
  REN2359                     5
  REN2703                    10
  REN2711                    14
  REN2724                    30
  REN2801                    45
  REN2877                    30
  REN2895                     5
  REN2937                     3
  REN2941                    14
  REN3177                    10
  REN3209                    10
  REN3211                     7
  REN3264                     5
  REN3340                     7
  REN3434                    10

Duration statistics:
count    27.000000
mean     12.962963
std      12.116364
min       3.000000
25%       5.000000
50%      10.000000
75%      14.000000
max      45.000000
Name: Rental_Duration_Days, dtype: float64

In [48]:
active_missing_mask = (
    df["Expected_Return_Date"].isna() &
    (df["Rental_Status"] == "Active")
)

df.loc[active_missing_mask, "Expected_Return_Date"] = (
    df.loc[active_missing_mask, "Rental_Start_Date"]
    + pd.to_timedelta(
        df.loc[active_missing_mask, "Rental_Duration_Days"],
        unit="D"
    )
)

print(
    "Expected_Return_Date missing after imputation:",
    df["Expected_Return_Date"].isna().sum()
)

print(
    "Active rentals still missing:",
    df.loc[
        df["Rental_Status"] == "Active",
        "Expected_Return_Date"
    ].isna().sum()
)

Expected_Return_Date missing after imputation: 146
Active rentals still missing: 0

In [49]:
return_missing = df["Return_Date"].isna()
actual_missing = df["Actual_Return_Date"].isna()

print("Both missing:", (return_missing & actual_missing).sum())
print("Return_Date only missing:", (return_missing & ~actual_missing).sum())
print("Actual_Return_Date only missing:", (~return_missing & actual_missing).sum())

Both missing: 492
Return_Date only missing: 0
Actual_Return_Date only missing: 0

In [50]:
missing_return_records = df[
    df["Actual_Return_Date"].isna()
]

print(
    pd.crosstab(
        missing_return_records["Rental_Status"],
        missing_return_records["Booking_Status"]
    )
)

Booking_Status  Cancelled  Confirmed
Rental_Status
Active                  0        346
Canceled                2          0
Cancelled             144          0

In [51]:
print(
    missing_return_records[
        [
            "Rental_Status",
            "Booking_Status",
            "Cancellation_Status"
        ]
    ].value_counts()
)

Rental_Status  Booking_Status  Cancellation_Status
Active         Confirmed       Not Cancelled          346
Cancelled      Cancelled       Cancelled              144
Canceled       Cancelled       Cancelled                2
Name: count, dtype: int64

In [52]:
print("Before:")
print(df["Rental_Status"].value_counts())

df["Rental_Status"] = df["Rental_Status"].replace({
    "Canceled": "Cancelled",
    "returned": "Returned"
})

print("\nAfter:")
print(df["Rental_Status"].value_counts())

Before:
Rental_Status
Returned     3005
Active        346
Cancelled     144
returned       23
Canceled        2
Name: count, dtype: int64

After:
Rental_Status
Returned     3028
Active        346
Cancelled     146
Name: count, dtype: int64

In [53]:
pincode_missing = df[df["Customer_Pincode"].isna()]

print("Missing pincodes:", len(pincode_missing))

print("\nCustomer Type:")
print(pincode_missing["Customer_Type"].value_counts())

print("\nArea:")
print(pincode_missing["Area"].value_counts())

Missing pincodes: 122

Customer Type:
Customer_Type
Individual Patient    41
Home Care             35
Hospital              23
Clinic                18
Diagnostic Center      5
Name: count, dtype: int64

Area:
Area
Erandwane        13
Hinjawadi        12
Wakad            11
Dhankawadi       11
Wanowrie          9
Hadapsar          9
Viman Nagar       7
Pimpri            7
Vishrantwadi      6
Shivajinagar      6
Aundh             6
Baner             5
Kharadi           5
Koregaon Park     4
Bibwewadi         4
Chinchwad         3
Camp              2
Kothrud           2
Name: count, dtype: int64

In [54]:
area_pincode = (
    df[df["Customer_Pincode"].notna()]
    .groupby("Area")["Customer_Pincode"]
    .nunique()
    .sort_values(ascending=False)
)

print(area_pincode)

Area
Aundh            20
Baner            20
Bibwewadi        20
Camp             20
Chinchwad        20
Dhankawadi       20
Erandwane        20
Hadapsar         20
Hinjawadi        20
Kharadi          20
Koregaon Park    20
Kothrud          20
Pimpri           20
Shivajinagar     20
Viman Nagar      20
Vishrantwadi     20
Wakad            20
Wanowrie         20
Name: Customer_Pincode, dtype: int64

In [55]:
print("\nAreas with multiple pincodes:")
print(area_pincode[area_pincode > 1])

Areas with multiple pincodes:
Area
Aundh            20
Baner            20
Bibwewadi        20
Camp             20
Chinchwad        20
Dhankawadi       20
Erandwane        20
Hadapsar         20
Hinjawadi        20
Kharadi          20
Koregaon Park    20
Kothrud          20
Pimpri           20
Shivajinagar     20
Viman Nagar      20
Vishrantwadi     20
Wakad            20
Wanowrie         20
Name: Customer_Pincode, dtype: int64

In [56]:
print(
    df[df["Customer_Pincode"].isna()]["Equipment_Category"]
    .value_counts()
)

Equipment_Category
Respiratory Equipment      38
Patient Care Equipment     27
Mobility Equipment         25
Surgical Equipment         16
Diagnostic Equipment        7
Monitoring Equipment        6
Critical Care Equipment     3
Name: count, dtype: int64

In [57]:
print(
    df[df["Customer_Pincode"].isna()]["Equipment"]
    .value_counts()
)

Equipment
Hospital Bed           17
Wheelchair             14
Suction Machine        11
CPAP Machine           11
Fowler Bed             10
BiPAP Machine          10
Nebulizer               9
Oxygen Concentrator     8
ECG Machine             7
Commode Chair           6
Patient Monitor         6
Walker                  5
Surgical Loupe          4
Infusion Pump           2
Ventilator              1
Surgical Headlight      1
Name: count, dtype: int64

In [58]:
df["Customer_Pincode_Missing"] = df["Customer_Pincode"].isna().astype(int)

print(df["Customer_Pincode_Missing"].value_counts())

Customer_Pincode_Missing
0    3398
1     122
Name: count, dtype: int64

In [59]:
equipment_missing = df[df["Equipment_ID"].isna()]

print("Records with missing Equipment_ID:", len(equipment_missing))

print("\nEquipment:")
print(equipment_missing["Equipment"].value_counts())

print("\nEquipment Category:")
print(equipment_missing["Equipment_Category"].value_counts())

print("\nAcquisition_Date missing:")
print(equipment_missing["Acquisition_Date"].isna().sum())

print("\nEquipment_Age_Years missing:")
print(equipment_missing["Equipment_Age_Years"].isna().sum())

Records with missing Equipment_ID: 146

Equipment:
Equipment
Hospital Bed           21
Wheelchair             20
CPAP Machine           15
Oxygen Concentrator    13
Suction Machine        13
Fowler Bed             10
Patient Monitor         9
Commode Chair           8
Nebulizer               7
ECG Machine             5
BiPAP Machine           5
Infusion Pump           5
Surgical Loupe          4
Walker                  4
Surgical Headlight      3
Ventilator              3
WHEELCHAIR              1
Name: count, dtype: int64

Equipment Category:
Equipment_Category
Respiratory Equipment      40
Mobility Equipment         33
Patient Care Equipment     31
Surgical Equipment         20
Monitoring Equipment        9
Critical Care Equipment     8
Diagnostic Equipment        5
Name: count, dtype: int64

Acquisition_Date missing:
146

Equipment_Age_Years missing:
146

In [60]:
equipment_age_check = df[
    df["Acquisition_Date"].notna() &
    df["Equipment_Age_Years"].notna()
].copy()

print("Records available for checking:", len(equipment_age_check))

print(
    equipment_age_check[
        [
            "Acquisition_Date",
            "Equipment_Age_Years"
        ]
    ].head(10)
)

Records available for checking: 3374
  Acquisition_Date  Equipment_Age_Years
0       2024-02-15                  2.5
1       2025-01-03                  1.6
2       2024-12-09                  1.6
3       2023-06-13                  3.1
4       2023-09-08                  2.9
5       2022-02-05                  4.5
6       2025-01-04                  1.6
7       2023-01-10                  3.6
8       2022-10-28                  3.8
9       2022-06-19                  4.1

In [61]:
import numpy as np

age_on_rental = (
    (df["Rental_Date"] - df["Acquisition_Date"]).dt.days / 365.25
)

age_check = df[
    df["Acquisition_Date"].notna() &
    df["Equipment_Age_Years"].notna()
].copy()

age_check["Calculated_Age"] = age_on_rental[
    age_check.index
]

age_check["Difference"] = (
    age_check["Equipment_Age_Years"] -
    age_check["Calculated_Age"]
).abs()

print(age_check["Difference"].describe())

count    3374.000000
mean        1.077973
std         0.790239
min         0.000137
25%         0.347416
50%         0.970602
75%         1.785934
max         2.627789
Name: Difference, dtype: float64

In [62]:
age_complete = df[
    df["Acquisition_Date"].notna() &
    df["Equipment_Age_Years"].notna()
].copy()

age_complete["Implied_Reference_Date"] = (
    age_complete["Acquisition_Date"]
    + pd.to_timedelta(
        age_complete["Equipment_Age_Years"] * 365.25,
        unit="D"
    )
)

print(
    age_complete[
        [
            "Acquisition_Date",
            "Equipment_Age_Years",
            "Implied_Reference_Date"
        ]
    ].head(20).to_string(index=False)
)

Acquisition_Date  Equipment_Age_Years        Implied_Reference_Date
      2024-02-15                  2.5 2026-08-16 03:00:00.000000000
      2025-01-03                  1.6 2026-08-10 09:36:00.000000000
      2024-12-09                  1.6 2026-07-16 09:36:00.000000000
      2023-06-13                  3.1 2026-07-19 06:36:00.000000008
      2023-09-08                  2.9 2026-08-02 05:23:59.999999991
      2022-02-05                  4.5 2026-08-06 15:00:00.000000000
      2025-01-04                  1.6 2026-08-11 09:36:00.000000000
      2023-01-10                  3.6 2026-08-16 21:36:00.000000008
      2022-10-28                  3.8 2026-08-15 22:48:00.000000000
      2022-06-19                  4.1 2026-07-25 12:35:59.999999991
      2024-04-22                  2.3 2026-08-10 01:47:59.999999991
      2024-12-01                  1.7 2026-08-13 22:12:00.000000000
      2025-06-25                  1.1 2026-07-31 18:36:00.000000000
      2022-05-28                  4.2 2026-08-09 01:12:00.000000000
      2025-02-15                  1.5 2026-08-16 21:00:00.000000000
      2023-01-10                  3.6 2026-08-16 21:36:00.000000008
      2023-09-04                  2.9 2026-07-29 05:23:59.999999991
      2023-03-12                  3.4 2026-08-04 20:23:59.999999991
      2023-05-24                  3.2 2026-08-04 19:12:00.000000000
      2022-10-26                  3.8 2026-08-13 22:48:00.000000000

In [63]:
median_reference_date = age_complete["Implied_Reference_Date"].median()

print("Median implied reference date:")
print(median_reference_date)

print("\nMinimum:")
print(age_complete["Implied_Reference_Date"].min())

print("\nMaximum:")
print(age_complete["Implied_Reference_Date"].max())

Median implied reference date:
2026-08-04 11:24:00

Minimum:
2026-07-14 15:00:00

Maximum:
2026-08-18 22:48:00

In [64]:
equipment_fields = [
    "Equipment_ID",
    "Acquisition_Date",
    "Equipment_Age_Years"
]

print(
    df[equipment_fields]
    .isna()
    .value_counts()
)

Equipment_ID  Acquisition_Date  Equipment_Age_Years
False         False             False                  3374
True          True              True                    146
Name: count, dtype: int64

In [65]:
maintenance_missing = df[
    df["Maintenance_Date"].isna() |
    df["Next_Maintenance_Due"].isna()
]

print("Records with either maintenance date missing:", len(maintenance_missing))

print("\nMaintenance_Date missing by Rental_Status:")
print(
    df[df["Maintenance_Date"].isna()]["Rental_Status"].value_counts()
)

print("\nNext_Maintenance_Due missing by Rental_Status:")
print(
    df[df["Next_Maintenance_Due"].isna()]["Rental_Status"].value_counts()
)

Records with either maintenance date missing: 343

Maintenance_Date missing by Rental_Status:
Rental_Status
Cancelled    146
Returned      89
Active        12
Name: count, dtype: int64

Next_Maintenance_Due missing by Rental_Status:
Rental_Status
Cancelled    146
Returned      90
Active        10
Name: count, dtype: int64

In [66]:
maintenance_status = df[
    ["Maintenance_Date", "Next_Maintenance_Due"]
].isna()

print(maintenance_status.value_counts())

Maintenance_Date  Next_Maintenance_Due
False             False                   3177
True              True                     150
                  False                     97
False             True                      96
Name: count, dtype: int64

In [67]:
print(
    df.loc[
        maintenance_status["Maintenance_Date"] !=
        maintenance_status["Next_Maintenance_Due"],
        [
            "Rental_ID",
            "Equipment_ID",
            "Equipment",
            "Maintenance_Date",
            "Next_Maintenance_Due",
            "Rental_Status"
        ]
    ].to_string(index=False)
)

Rental_ID Equipment_ID           Equipment Maintenance_Date Next_Maintenance_Due Rental_Status
  REN0011       CC-001       Commode Chair       2025-08-07                  NaT      Returned
  REN0014       CP-009        CPAP Machine              NaT           2025-08-06      Returned
  REN0058       VT-006          Ventilator       2023-08-14                  NaT      Returned
  REN0064       SH-005  Surgical Headlight              NaT           2025-12-06      Returned
  REN0106       CP-007        CPAP Machine       2026-04-29                  NaT      Returned
  REN0122       BP-004       BiPAP Machine              NaT           2026-02-23      Returned
  REN0135       OC-003 Oxygen Concentrator       2025-07-09                  NaT      Returned
  REN0157       HB-013        Hospital Bed              NaT           2026-03-16      Returned
  REN0167       WK-004              Walker       2024-10-16                  NaT      Returned
  REN0168       PM-007     Patient Monitor       2024-02-25                  NaT      Returned
  REN0179       HB-009        Hospital Bed       2023-06-27                  NaT      Returned
  REN0181       OC-009 Oxygen Concentrator       2025-05-23                  NaT      Returned
  REN0215      ECG-001         ECG Machine              NaT           2026-02-05      Returned
  REN0242       CC-007       Commode Chair              NaT           2024-08-07      Returned
  REN0248       WK-001              Walker              NaT           2025-03-20        Active
  REN0276       HB-022        Hospital Bed       2023-05-17                  NaT      Returned
  REN0277       VT-001          Ventilator       2025-06-25                  NaT      Returned
  REN0283       HB-002        Hospital Bed       2024-08-21                  NaT      Returned
  REN0289       HB-016        Hospital Bed              NaT           2025-11-01        Active
  REN0293       HB-004        Hospital Bed       2026-06-21                  NaT      Returned
  REN0305       HB-023        Hospital Bed       2024-01-10                  NaT      Returned
  REN0330      ECG-009         ECG Machine              NaT           2026-09-26      Returned
  REN0350       BP-010       BiPAP Machine              NaT           2025-11-03      Returned
  REN0356       WC-014          Wheelchair       2026-01-27                  NaT      Returned
  REN0359       SM-012     Suction Machine              NaT           2025-12-29      Returned
  REN0381       OC-011 Oxygen Concentrator              NaT           2025-07-02        Active
  REN0387       WC-018          Wheelchair       2025-03-11                  NaT        Active
  REN0405       WC-013          Wheelchair       2026-02-24                  NaT      Returned
  REN0424       VT-006          Ventilator       2023-08-14                  NaT      Returned
  REN0429       NB-005           Nebulizer       2025-09-26                  NaT      Returned
  REN0433       WC-018          Wheelchair       2025-03-11                  NaT      Returned
  REN0438       HB-002        Hospital Bed       2024-08-21                  NaT      Returned
  REN0456       IP-003       Infusion Pump       2025-06-17                  NaT        Active
  REN0462       NB-012           Nebulizer       2024-10-27                  NaT      Returned
  REN0480       NB-012           Nebulizer       2024-10-27                  NaT      Returned
  REN0527       WK-006              Walker              NaT           2025-09-28      Returned
  REN0538      ECG-005         ECG Machine       2022-08-13                  NaT      Returned
  REN0598       FB-012          Fowler Bed              NaT           2026-04-09      Returned
  REN0599       SM-003     Suction Machine       2026-01-30                  NaT      Returned
  REN0627       PM-005     Patient Monitor              NaT           2025-05-13      Returned
  REN0628       HB-017        Hospital Bed              NaT           2026-08-26      Returned
  REN0636       WC-006          Wheelchair       2024-01-01                  NaT      Returned
  REN0639      ECG-009         ECG Machine              NaT           2026-09-26        Active
  REN0640       CC-006       Commode Chair       2025-03-18                  NaT      Returned
  REN0647       WC-006          Wheelchair              NaT           2024-03-31      Returned
  REN0676       HB-018        Hospital Bed       2025-07-16                  NaT      Returned
  REN0776       OC-010 Oxygen Concentrator       2023-03-21                  NaT      Returned
  REN0785       WC-009          Wheelchair       2024-11-16                  NaT      Returned
  REN0802       WC-018          Wheelchair              NaT           2026-03-11      Returned
  REN0820       SH-001  Surgical Headlight       2023-01-30                  NaT      Returned
  REN0824       HB-023        Hospital Bed       2024-01-10                  NaT      Returned
  REN0833       FB-014          Fowler Bed              NaT           2025-10-14      Returned
  REN0848       WC-019          Wheelchair              NaT           2026-08-25      Returned
  REN0857       NB-002           Nebulizer       2026-04-29                  NaT      Returned
  REN0864       VT-002          Ventilator       2026-04-04                  NaT      Returned
  REN0865       HB-009        Hospital Bed              NaT           2023-09-25      Returned
  REN0887      ECG-003         ECG Machine       2023-07-22                  NaT        Active
  REN0890       OC-008 Oxygen Concentrator              NaT           2023-08-03      Returned
  REN0953       BP-004       BiPAP Machine              NaT           2026-02-23      Returned
  REN0972       SH-001  Surgical Headlight              NaT           2023-07-29      Returned
  REN0976       NB-002           Nebulizer              NaT           2026-08-27      Returned
  REN0997       HB-016        Hospital Bed       2024-11-01                  NaT      Returned
  REN1000       WC-005          Wheelchair       2026-02-09                  NaT      Returned
  REN1008       WK-006              Walker       2025-05-31                  NaT      Returned
  REN1019       FB-008          Fowler Bed              NaT           2027-07-02      Returned
  REN1024       HB-001        Hospital Bed              NaT           2025-11-24      Returned
  REN1029       HB-021        Hospital Bed       2026-06-19                  NaT      Returned
  REN1056       OC-013 Oxygen Concentrator              NaT           2025-03-06      Returned
  REN1066       WK-003              Walker       2024-11-09                  NaT      Returned
  REN1067       SH-003  Surgical Headlight       2024-03-16                  NaT      Returned
  REN1120       BP-004       BiPAP Machine       2025-02-23                  NaT      Returned
  REN1125       NB-008           Nebulizer       2025-07-25                  NaT      Returned
  REN1133       OC-001 Oxygen Concentrator              NaT           2026-01-07      Returned
  REN1147       HB-004        Hospital Bed              NaT           2026-12-18      Returned
  REN1150       WK-004              Walker              NaT           2025-10-16      Returned
  REN1159       CP-008        CPAP Machine              NaT           2025-08-20      Returned
  REN1203       SM-004     Suction Machine       2023-10-14                  NaT        Active
  REN1209       NB-011           Nebulizer              NaT           2023-10-03        Active
  REN1213       PM-005     Patient Monitor              NaT           2025-05-13      Returned
  REN1269       FB-001          Fowler Bed              NaT           2026-06-10      Returned
  REN1287       SM-008     Suction Machine              NaT           2026-04-26      Returned
  REN1314       FB-001          Fowler Bed              NaT           2026-06-10      Returned
  REN1325       SM-013     Suction Machine       2024-05-07                  NaT      Returned
  REN1328       CC-007       Commode Chair       2024-05-09                  NaT      Returned
  REN1347      ECG-001         ECG Machine       2025-11-07                  NaT        Active
  REN1365       WC-012          Wheelchair       2026-05-02                  NaT      Returned
  REN1371       WC-015          Wheelchair              NaT           2026-11-16      Returned
  REN1394       CP-013        CPAP Machine              NaT           2027-03-03      Returned
  REN1451       WK-004              Walker       2024-10-16                  NaT        Active
  REN1457       CP-011        CPAP Machine       2025-12-26                  NaT      Returned
  REN1542      ECG-006         ECG Machine       2026-03-18                  NaT      Returned
  REN1549       OC-005 Oxygen Concentrator              NaT           2026-10-14      Returned
  REN1565       WC-001          Wheelchair              NaT           2025-11-22      Returned
  REN1566       SM-010     Suction Machine       2026-06-17                  NaT      Returned
  REN1577       FB-009          Fowler Bed              NaT           2026-12-15      Returned
  REN1636       FB-012          Fowler Bed              NaT           2026-04-09      Returned
  REN1642       CC-006       Commode Chair              NaT           2025-07-16        Active
  REN1643       HB-023        Hospital Bed              NaT           2024-05-09      Returned
  REN1663       WC-014          Wheelchair       2026-01-27                  NaT      Returned
  REN1673       CP-015        CPAP Machine              NaT           2023-07-18      Returned
  REN1686       IP-010       Infusion Pump              NaT           2024-06-03      Returned
  REN1740       NB-004           Nebulizer              NaT           2023-12-01      Returned
  REN1778       FB-011          Fowler Bed       2023-03-15                  NaT      Returned
  REN1795       BP-010       BiPAP Machine       2025-05-07                  NaT      Returned
  REN1798       CC-005       Commode Chair       2024-10-24                  NaT      Returned
  REN1842       WK-005              Walker       2024-06-28                  NaT      Returned
  REN1868       WK-006              Walker              NaT           2025-09-28        Active
  REN1884       WC-015          Wheelchair       2025-11-16                  NaT      Returned
  REN1896      ECG-001         ECG Machine              NaT           2026-02-05      Returned
  REN1908       SM-012     Suction Machine       2025-07-02                  NaT      Returned
  REN1919       WC-003          Wheelchair              NaT           2024-08-14      Returned
  REN1922       WK-007              Walker       2023-01-01                  NaT      Returned
  REN1923       VT-004          Ventilator              NaT           2025-04-12        Active
  REN1964       OC-016 Oxygen Concentrator              NaT           2026-09-16      Returned
  REN1974       OC-016 Oxygen Concentrator       2026-06-18                  NaT      Returned
  REN1978       FB-007          Fowler Bed              NaT           2023-10-19      Returned
  REN1992       WC-010          Wheelchair              NaT           2027-01-15      Returned
  REN2002       HB-021        Hospital Bed       2026-06-19                  NaT      Returned
  REN2054       NB-003           Nebulizer              NaT           2026-01-05      Returned
  REN2072       NB-009           Nebulizer       2025-08-24                  NaT      Returned
  REN2074       VT-002          Ventilator              NaT           2026-08-02      Returned
  REN2079       SH-004  Surgical Headlight              NaT           2026-08-20      Returned
  REN2094       SM-007     Suction Machine              NaT           2025-11-08      Returned
  REN2104       WC-003          Wheelchair              NaT           2024-08-14      Returned
  REN2106       WC-008          Wheelchair       2025-04-12                  NaT      Returned
  REN2110       HB-015        Hospital Bed       2025-01-01                  NaT      Returned
  REN2124       FB-004          Fowler Bed              NaT           2026-11-03      Returned
  REN2129       BP-005       BiPAP Machine              NaT           2025-01-13      Returned
  REN2139       NB-006           Nebulizer       2025-08-23                  NaT      Returned
  REN2152       CC-008       Commode Chair              NaT           2026-12-20      Returned
  REN2174       WC-004          Wheelchair              NaT           2025-07-17      Returned
  REN2203       VT-004          Ventilator       2024-10-14                  NaT      Returned
  REN2204      ECG-005         ECG Machine       2022-08-13                  NaT      Returned
  REN2218       HB-015        Hospital Bed              NaT           2025-04-01        Active
  REN2237       WC-003          Wheelchair              NaT           2024-08-14      Returned
  REN2263       IP-003       Infusion Pump              NaT           2025-09-15      Returned
  REN2264       OC-009 Oxygen Concentrator              NaT           2025-11-19      Returned
  REN2277       SH-006  Surgical Headlight              NaT           2025-07-26      Returned
  REN2299       WC-009          Wheelchair       2024-11-16                  NaT      Returned
  REN2319      ECG-003         ECG Machine       2023-07-22                  NaT      Returned
  REN2330       IP-009       Infusion Pump       2025-01-24                  NaT        Active
  REN2346       HB-019        Hospital Bed       2024-04-14                  NaT      Returned
  REN2355       NB-012           Nebulizer              NaT           2025-04-25      Returned
  REN2370       CC-009       Commode Chair              NaT           2026-07-18      Returned
  REN2371       CP-004        CPAP Machine       2023-10-18                  NaT      Returned
  REN2411       OC-006 Oxygen Concentrator              NaT           2025-04-24      Returned
  REN2424       HB-003        Hospital Bed              NaT           2024-09-25      Returned
  REN2426       CC-008       Commode Chair              NaT           2026-12-20      Returned
  REN2445       CP-009        CPAP Machine              NaT           2025-08-06      Returned
  REN2456       CP-004        CPAP Machine              NaT           2024-01-16        Active
  REN2461      ECG-004         ECG Machine              NaT           2025-04-30      Returned
  REN2478       WC-003          Wheelchair              NaT           2024-08-14      Returned
  REN2480       PM-013     Patient Monitor       2024-09-22                  NaT      Returned
  REN2483       OC-016 Oxygen Concentrator              NaT           2026-09-16      Returned
  REN2528       SL-002      Surgical Loupe              NaT           2026-01-01      Returned
  REN2539       SH-008  Surgical Headlight       2025-11-10                  NaT      Returned
  REN2582       FB-013          Fowler Bed       2025-09-22                  NaT      Returned
  REN2593       WC-015          Wheelchair              NaT           2026-11-16      Returned
  REN2655       BP-001       BiPAP Machine       2025-12-27                  NaT      Returned
  REN2660       PM-012     Patient Monitor       2024-10-07                  NaT        Active
  REN2675       WC-008          Wheelchair       2025-04-12                  NaT      Returned
  REN2678       OC-002 Oxygen Concentrator       2025-09-17                  NaT      Returned
  REN2685       SM-004     Suction Machine              NaT           2024-01-12      Returned
  REN2700       OC-005 Oxygen Concentrator              NaT           2026-10-14      Returned
  REN2761       WK-007              Walker       2023-01-01                  NaT      Returned
  REN2794       CC-008       Commode Chair              NaT           2026-12-20      Returned
  REN2806       NB-003           Nebulizer       2025-10-07                  NaT      Returned
  REN2865       WC-003          Wheelchair              NaT           2024-08-14      Returned
  REN2867       NB-012           Nebulizer       2024-10-27                  NaT      Returned
  REN2886       OC-001 Oxygen Concentrator       2025-09-09                  NaT        Active
  REN2923       OC-006 Oxygen Concentrator       2024-10-26                  NaT      Returned
  REN2925       BP-008       BiPAP Machine       2024-11-06                  NaT      Returned
  REN2933       CC-006       Commode Chair              NaT           2025-07-16      Returned
  REN2949       PM-013     Patient Monitor              NaT           2025-03-21      Returned
  REN2953       HB-012        Hospital Bed       2023-10-26                  NaT      Returned
  REN2986       CC-008       Commode Chair              NaT           2026-12-20        Active
  REN3051       HB-021        Hospital Bed       2026-06-19                  NaT      Returned
  REN3126       WC-008          Wheelchair       2025-04-12                  NaT      Returned
  REN3136       SH-001  Surgical Headlight              NaT           2023-07-29      Returned
  REN3137       BP-003       BiPAP Machine       2023-01-31                  NaT      Returned
  REN3139       VT-001          Ventilator              NaT           2025-10-23      Returned
  REN3157       NB-012           Nebulizer              NaT           2025-04-25      Returned
  REN3186       WC-001          Wheelchair       2025-08-24                  NaT      Returned
  REN3188       CC-006       Commode Chair       2025-03-18                  NaT      Returned
  REN3198       HB-013        Hospital Bed       2025-11-16                  NaT      Returned
  REN3210       OC-011 Oxygen Concentrator              NaT           2025-07-02      Returned
  REN3240       SM-002     Suction Machine              NaT           2024-04-25      Returned
  REN3260       SL-002      Surgical Loupe              NaT           2026-01-01      Returned
  REN3281       CC-008       Commode Chair       2026-06-23                  NaT      Returned
  REN3324       HB-006        Hospital Bed       2023-10-02                  NaT      Returned
  REN3393       FB-013          Fowler Bed              NaT           2026-01-20      Returned
  REN3400       WC-019          Wheelchair       2026-05-27                  NaT      Returned
  REN3498       CP-019        CPAP Machine              NaT           2025-08-24      Returned

In [68]:
maintenance_complete = df[
    df["Maintenance_Date"].notna() &
    df["Next_Maintenance_Due"].notna()
].copy()

maintenance_gap = (
    maintenance_complete["Next_Maintenance_Due"] -
    maintenance_complete["Maintenance_Date"]
).dt.days

print(maintenance_gap.describe())

count    3177.000000
mean      189.779666
std       103.604201
min        90.000000
25%       120.000000
50%       180.000000
75%       180.000000
max       365.000000
dtype: float64

In [69]:
missing_report = pd.DataFrame({
    "Missing_Count": df.isna().sum(),
    "Missing_Percentage": (
        df.isna().sum() / len(df) * 100
    ).round(2)
})

print(
    missing_report[
        missing_report["Missing_Count"] > 0
    ]
)

                      Missing_Count  Missing_Percentage
Customer_Rating                 247                7.02
Return_Date                     492               13.98
Expected_Return_Date            146                4.15
Actual_Return_Date              492               13.98
Customer_Pincode                122                3.47
Equipment_ID                    146                4.15
Acquisition_Date                146                4.15
Maintenance_Date                247                7.02
Next_Maintenance_Due            246                6.99
Equipment_Age_Years             146                4.15

In [70]:
df["Equipment_Info_Missing"] = (
    df["Equipment_ID"].isna()
).astype(int)

print(df["Equipment_Info_Missing"].value_counts())

Equipment_Info_Missing
0    3374
1     146
Name: count, dtype: int64

In [71]:
print("Exact duplicate rows:", df.duplicated().sum())
print("Duplicate Rental_IDs:", df["Rental_ID"].duplicated().sum())

Exact duplicate rows: 20
Duplicate Rental_IDs: 20

In [72]:
df = df.drop_duplicates().reset_index(drop=True)

print("Rows after removing duplicates:", df.shape[0])
print("Exact duplicate rows remaining:", df.duplicated().sum())
print("Duplicate Rental_IDs remaining:", df["Rental_ID"].duplicated().sum())

Rows after removing duplicates: 3500
Exact duplicate rows remaining: 0
Duplicate Rental_IDs remaining: 0

In [74]:
categorical_columns = df.select_dtypes(include="object").columns

for col in categorical_columns:
    print(f"\n--- {col} ---")
    print(df[col].value_counts(dropna=False))

--- Rental_ID ---
Rental_ID
REN3500    1
REN0001    1
REN0002    1
REN0003    1
REN0004    1
          ..
REN0017    1
REN0016    1
REN0015    1
REN0014    1
REN0013    1
Name: count, Length: 3500, dtype: int64

--- Customer_ID ---
Customer_ID
CUST153    20
CUST160    18
CUST349    16
CUST173    16
CUST356    16
           ..
CUST459     1
CUST435     1
CUST513     1
CUST035     1
CUST596     1
Name: count, Length: 579, dtype: int64

--- Customer_Type ---
Customer_Type
Home Care             1112
Individual Patient     993
Hospital               720
Clinic                 491
Diagnostic Center      184
Name: count, dtype: int64

--- Area ---
Area
Dhankawadi       260
Hinjawadi        235
Koregaon Park    224
Wanowrie         221
Erandwane        219
Shivajinagar     211
Hadapsar         211
Vishrantwadi     209
Viman Nagar      207
Bibwewadi        193
Chinchwad        193
Wakad            177
Kothrud          169
Pimpri           169
Kharadi          164
Aundh            153
Camp             150
Baner            135
Name: count, dtype: int64

--- Equipment ---
Equipment
Wheelchair             467
Hospital Bed           448
Oxygen Concentrator    346
CPAP Machine           301
Fowler Bed             285
Suction Machine        213
BiPAP Machine          200
Nebulizer              194
Patient Monitor        192
Commode Chair          186
ECG Machine            159
Infusion Pump          121
Surgical Headlight     112
Walker                 104
Ventilator              82
Surgical Loupe          76
WHEELCHAIR               8
hospital bed             5
oxygen concentrator      1
Name: count, dtype: int64

--- Equipment_Category ---
Equipment_Category
Respiratory Equipment      1042
Mobility Equipment          765
Patient Care Equipment      738
Surgical Equipment          401
Critical Care Equipment     203
Monitoring Equipment        192
Diagnostic Equipment        159
Name: count, dtype: int64

--- Payment_Mode ---
Payment_Mode
UPI              1454
Credit Card       727
Bank Transfer     682
Debit Card        342
Cash              295
Name: count, dtype: int64

--- Rental_Status ---
Rental_Status
Returned     3009
Active        346
Cancelled     145
Name: count, dtype: int64

--- Equipment_Condition ---
Equipment_Condition
Good         2087
Excellent     923
Fair          448
GOOD           26
excellent       9
fair            7
Name: count, dtype: int64

--- Booking_Status ---
Booking_Status
Completed    3009
Confirmed     346
Cancelled     145
Name: count, dtype: int64

--- Cancellation_Status ---
Cancellation_Status
Not Cancelled    3355
Cancelled         145
Name: count, dtype: int64

--- Equipment_ID ---
Equipment_ID
NaN       145
WC-001     27
WC-003     25
WC-012     24
WC-011     24
         ...
SL-007     10
VT-003      9
VT-007      9
VT-008      9
SL-003      9
Name: count, Length: 203, dtype: int64

In [75]:
df["Equipment"] = df["Equipment"].replace({
    "WHEELCHAIR": "Wheelchair",
    "hospital bed": "Hospital Bed",
    "oxygen concentrator": "Oxygen Concentrator"
})

df["Equipment_Condition"] = df["Equipment_Condition"].replace({
    "GOOD": "Good",
    "excellent": "Excellent",
    "fair": "Fair"
})

In [76]:
print(df["Equipment"].value_counts())
print()
print(df["Equipment_Condition"].value_counts())

Equipment
Wheelchair             475
Hospital Bed           453
Oxygen Concentrator    347
CPAP Machine           301
Fowler Bed             285
Suction Machine        213
BiPAP Machine          200
Nebulizer              194
Patient Monitor        192
Commode Chair          186
ECG Machine            159
Infusion Pump          121
Surgical Headlight     112
Walker                 104
Ventilator              82
Surgical Loupe          76
Name: count, dtype: int64

Equipment_Condition
Good         2113
Excellent     932
Fair          455
Name: count, dtype: int64

In [77]:
categorical_columns = df.select_dtypes(include="object").columns

categorical_summary = pd.DataFrame({
    "Unique_Values": df[categorical_columns].nunique(),
    "Missing_Values": df[categorical_columns].isna().sum()
})

print(categorical_summary)

                     Unique_Values  Missing_Values
Rental_ID                     3500               0
Customer_ID                    579               0
Customer_Type                    5               0
Area                            18               0
Equipment                       16               0
Equipment_Category               7               0
Payment_Mode                     5               0
Rental_Status                    3               0
Equipment_Condition              3               0
Booking_Status                   3               0
Cancellation_Status              2               0
Equipment_ID                   202             145

In [78]:
numeric_columns = df.select_dtypes(include=["int64", "float64"]).columns

print(df[numeric_columns].describe().T)

                           count           mean          std       min  \
Rental_Duration_Days      3500.0      12.930286    10.511646       1.0
Daily_Rate                3500.0     321.757143   192.391460      60.0
Total_Rental_Amount       3500.0    4132.822857  4510.005273      70.0
Security_Deposit          3500.0    5367.534286  3454.787741     660.0
Delivery_Charge           3500.0     334.742857   151.905369     100.0
Maintenance_Cost          3500.0     101.579429   159.158534       0.0
Customer_Rating           3254.0       4.329287     0.576174       3.0
Customer_Pincode          3378.0  411035.013321    15.986117  411007.0
Equipment_Age_Years       3355.0       2.800954     1.032226       1.0
Total_Inventory           3500.0      15.081143     4.968002       7.0
Available_Units_At_Start  3500.0      11.269143     4.363010       3.0
Customer_Pincode_Missing  3500.0       0.034857     0.183444       0.0
Equipment_Info_Missing    3500.0       0.041429     0.199308       0.0

                               25%       50%       75%       max
Rental_Duration_Days           5.0      10.0      21.0      60.0
Daily_Rate                   160.0     320.0     410.0    1180.0
Total_Rental_Amount         1197.5    2520.0    5200.0   47700.0
Security_Deposit            2720.0    5040.0    7100.0   25700.0
Delivery_Charge              200.0     300.0     450.0    1000.0
Maintenance_Cost              28.0      57.0     109.0    2300.0
Customer_Rating                4.0       4.5       5.0       5.0
Customer_Pincode          411027.0  411040.0  411047.0  411058.0
Equipment_Age_Years            2.0       2.8       3.7       4.6
Total_Inventory               11.0      15.0      20.0      23.0
Available_Units_At_Start       8.0      11.0      14.0      23.0
Customer_Pincode_Missing       0.0       0.0       0.0       1.0
Equipment_Info_Missing         0.0       0.0       0.0       1.0

In [79]:
# 1. Check rental amount calculation
calculated_amount = (
    df["Rental_Duration_Days"] * df["Daily_Rate"]
)

amount_diff = (
    df["Total_Rental_Amount"] - calculated_amount
)

print("Rental amount differences:")
print(amount_diff.describe())

print("\nRows with differences:")
print((amount_diff != 0).sum())


# 2. Check inventory relationship
invalid_inventory = (
    df["Available_Units_At_Start"] > df["Total_Inventory"]
)

print("\nAvailable units greater than total inventory:")
print(invalid_inventory.sum())


# 3. Check rental duration
print("\nInvalid rental durations:")
print((df["Rental_Duration_Days"] <= 0).sum())


# 4. Check customer rating
invalid_rating = ~df["Customer_Rating"].isna() & (
    (df["Customer_Rating"] < 1) |
    (df["Customer_Rating"] > 5)
)

print("\nInvalid customer ratings:")
print(invalid_rating.sum())

Rental amount differences:
count     3500.000000
mean       -16.238571
std        452.701903
min     -20580.000000
25%          0.000000
50%          0.000000
75%          0.000000
max          0.000000
dtype: float64

Rows with differences:
10

Available units greater than total inventory:
0

Invalid rental durations:
0

Invalid customer ratings:
0

In [80]:
amount_mismatch = df[
    df["Total_Rental_Amount"] !=
    (df["Rental_Duration_Days"] * df["Daily_Rate"])
]

print(
    amount_mismatch[
        [
            "Rental_ID",
            "Rental_Duration_Days",
            "Daily_Rate",
            "Total_Rental_Amount"
        ]
    ].to_string(index=False)
)

Rental_ID  Rental_Duration_Days  Daily_Rate  Total_Rental_Amount
  REN0217                    60         170                 5100
  REN0972                    14         270                 2520
  REN1518                     5         810                 2700
  REN2203                    42         980                20580
  REN2222                     7         405                 1890
  REN2387                    20        1060                10600
  REN2402                     6         450                 1350
  REN2638                    45         780                23400
  REN2788                    20         360                 3600
  REN3132                    10         105                  700

In [81]:
df = df.rename(columns={
    "Total_Rental_Amount": "Total_Rental_Amount_Original"
})

df["Total_Rental_Amount"] = (
    df["Rental_Duration_Days"] * df["Daily_Rate"]
)

In [82]:
amount_diff = (
    df["Total_Rental_Amount"]
    - df["Total_Rental_Amount_Original"]
)

print("Rows corrected:", (amount_diff != 0).sum())
print("Remaining mismatches:", (
    df["Total_Rental_Amount"] !=
    df["Rental_Duration_Days"] * df["Daily_Rate"]
).sum())

Rows corrected: 10
Remaining mismatches: 0

In [83]:
id_cols = [
    "Daily_Rate",
    "Total_Rental_Amount",
    "Total_Rental_Amount_Original",
    "Security_Deposit",
    "Delivery_Charge",
    "Maintenance_Cost"
]

for col in id_cols:
    print(f"{col}: {(df[col] < 0).sum()} negative values")

Daily_Rate: 0 negative values
Total_Rental_Amount: 0 negative values
Total_Rental_Amount_Original: 0 negative values
Security_Deposit: 0 negative values
Delivery_Charge: 0 negative values
Maintenance_Cost: 0 negative values

In [84]:
outlier_columns = [
    "Rental_Duration_Days",
    "Daily_Rate",
    "Total_Rental_Amount",
    "Security_Deposit",
    "Delivery_Charge",
    "Maintenance_Cost",
    "Customer_Rating",
    "Equipment_Age_Years"
]

for col in outlier_columns:
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1

    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR

    outliers = df[
        (df[col] < lower_bound) |
        (df[col] > upper_bound)
    ][col].notna().sum()

    print(
        f"{col}: {outliers} outliers "
        f"(lower={lower_bound:.2f}, upper={upper_bound:.2f})"
    )

Rental_Duration_Days: 1 outliers (lower=-19.00, upper=45.00)
Daily_Rate: 83 outliers (lower=-215.00, upper=785.00)
Total_Rental_Amount: 273 outliers (lower=-4806.25, upper=11203.75)
Security_Deposit: 78 outliers (lower=-3850.00, upper=13670.00)
Delivery_Charge: 1 outliers (lower=-175.00, upper=825.00)
Maintenance_Cost: 279 outliers (lower=-93.50, upper=230.50)
Customer_Rating: 0 outliers (lower=2.50, upper=6.50)
Equipment_Age_Years: 0 outliers (lower=-0.55, upper=6.25)

In [85]:
for col in [
    "Rental_Duration_Days",
    "Daily_Rate",
    "Security_Deposit",
    "Delivery_Charge",
    "Maintenance_Cost"
]:
    print(f"\n===== {col} =====")
    print(
        df.nlargest(5, col)[
            [
                "Rental_ID",
                "Equipment",
                "Rental_Duration_Days",
                "Daily_Rate",
                "Total_Rental_Amount",
                "Security_Deposit",
                "Delivery_Charge",
                "Maintenance_Cost"
            ]
        ].to_string(index=False)
    )

===== Rental_Duration_Days =====
Rental_ID           Equipment  Rental_Duration_Days  Daily_Rate  Total_Rental_Amount  Security_Deposit  Delivery_Charge  Maintenance_Cost
  REN0217  Surgical Headlight                    60         170                10200              4200              150               380
  REN0049         ECG Machine                    45         530                23850              9800              350              1000
  REN0054       Commode Chair                    45          90                 4050              2100              250               170
  REN0074           Nebulizer                    45          90                 4050              1600              100               180
  REN0090 Oxygen Concentrator                    45         260                11700              5600              150               960

===== Daily_Rate =====
Rental_ID  Equipment  Rental_Duration_Days  Daily_Rate  Total_Rental_Amount  Security_Deposit  Delivery_Charge  Maintenance_Cost
  REN0243 Ventilator                     3        1180                 3540             20000              300               260
  REN1381 Ventilator                     7        1180                 8260             12980              500               223
  REN3139 Ventilator                     5        1180                 5900             18880              250               127
  REN3183 Ventilator                     7        1180                 8260             14160              400               154
  REN0012 Ventilator                     7        1170                 8190             21700              300               520

===== Security_Deposit =====
Rental_ID  Equipment  Rental_Duration_Days  Daily_Rate  Total_Rental_Amount  Security_Deposit  Delivery_Charge  Maintenance_Cost
  REN0353 Ventilator                     3        1030                 3090             25700              250               220
  REN0620 Ventilator                    14        1110                15540             25400              200              1300
  REN0094 Ventilator                    14        1010                14140             25100              200              1230
  REN0277 Ventilator                    30         980                29400             24900              350              1820
  REN0241 Ventilator                     5        1130                 5650             24800              200               500

===== Delivery_Charge =====
Rental_ID       Equipment  Rental_Duration_Days  Daily_Rate  Total_Rental_Amount  Security_Deposit  Delivery_Charge  Maintenance_Cost
  REN0763    Hospital Bed                    10         350                 3500              7000             1000                26
  REN0456   Infusion Pump                    14         350                 4900              5800              600               260
  REN0553   Commode Chair                    21         100                 2100              2200              600               120
  REN0694 Patient Monitor                     3         600                 1800             10000              600                80
  REN0709    CPAP Machine                     7         380                 2660              7600              600                86

===== Maintenance_Cost =====
Rental_ID       Equipment  Rental_Duration_Days  Daily_Rate  Total_Rental_Amount  Security_Deposit  Delivery_Charge  Maintenance_Cost
  REN0222 Patient Monitor                    45         580                26100              9700              350              2300
  REN0277      Ventilator                    30         980                29400             24900              350              1820
  REN0168 Patient Monitor                    30         630                18900             10600              250              1680
  REN0005      Ventilator                    21        1140                23940             20900              250              1650
  REN0508 Patient Monitor                    30         620                18600             12500              200              1360