In [4]:
from google.colab import files

uploaded = files.upload()

Saving cleaned_medical_equipment_dataset.csv to cleaned_medical_equipment_dataset.csv

In [5]:
import pandas as pd

file_path = "/content/cleaned_medical_equipment_dataset.csv"

df = pd.read_csv(file_path)

print("Dataset shape:", df.shape)
print("\nColumns:")
print(df.columns.tolist())

Dataset shape: (3500, 35)

Columns:
['Rental_ID', 'Rental_Date', 'Customer_ID', 'Customer_Type', 'Area', 'Equipment', 'Equipment_Category', 'Rental_Duration_Days', 'Daily_Rate', 'Total_Rental_Amount_Original', 'Security_Deposit', 'Delivery_Charge', 'Maintenance_Cost', 'Payment_Mode', 'Rental_Status', 'Equipment_Condition', 'Customer_Rating', 'Return_Date', 'Booking_Date', 'Rental_Start_Date', 'Expected_Return_Date', 'Actual_Return_Date', 'Booking_Status', 'Cancellation_Status', 'Customer_Pincode', 'Equipment_ID', 'Acquisition_Date', 'Maintenance_Date', 'Next_Maintenance_Due', 'Equipment_Age_Years', 'Total_Inventory', 'Available_Units_At_Start', 'Customer_Pincode_Missing', 'Equipment_Info_Missing', 'Total_Rental_Amount']

In [7]:
df.head()

,Rental_ID,Rental_Date,Customer_ID,Customer_Type,Area,Equipment,Equipment_Category,Rental_Duration_Days,Daily_Rate,Total_Rental_Amount_Original,...,Equipment_ID,Acquisition_Date,Maintenance_Date,Next_Maintenance_Due,Equipment_Age_Years,Total_Inventory,Available_Units_At_Start,Customer_Pincode_Missing,Equipment_Info_Missing,Total_Rental_Amount
0,REN0001,2026-02-17,CUST155,Individual Patient,Wanowrie,Oxygen Concentrator,Respiratory Equipment,21,260,5460,...,OC-005,2024-02-15,2026-06-16,2026-10-14,2.5,16,12,0,0,5460
1,REN0002,2026-07-18,CUST169,Diagnostic Center,Shivajinagar,Surgical Headlight,Surgical Equipment,7,170,1190,...,SH-006,2025-01-03,2025-04-27,2025-07-26,1.6,8,4,0,0,1190
2,REN0003,2026-06-18,CUST391,Hospital,Wakad,Oxygen Concentrator,Respiratory Equipment,3,300,900,...,OC-003,2024-12-09,2025-07-09,2026-07-09,1.6,16,8,0,0,900
3,REN0004,2026-04-01,CUST350,Diagnostic Center,Hinjawadi,BiPAP Machine,Respiratory Equipment,14,560,7840,...,BP-006,2023-06-13,2023-11-02,2024-04-30,3.1,11,6,0,0,7840
4,REN0005,2026-06-26,CUST357,Home Care,Baner,Ventilator,Critical Care Equipment,21,1140,23940,...,VT-004,2023-09-08,2024-10-14,2025-04-12,2.9,8,7,0,0,23940

In [8]:
date_columns = [
    "Rental_Date",
    "Booking_Date",
    "Rental_Start_Date",
    "Expected_Return_Date",
    "Actual_Return_Date",
    "Return_Date",
    "Acquisition_Date",
    "Maintenance_Date",
    "Next_Maintenance_Due"
]

for col in date_columns:
    print(f"\n{col}")
    print("Min:", df[col].min())
    print("Max:", df[col].max())

Rental_Date
Min: 2024-01-01
Max: 2026-07-31

Booking_Date
Min: 2023-12-22
Max: 2026-07-30

Rental_Start_Date
Min: 2024-01-01
Max: 2026-07-31

Expected_Return_Date

TypeError: '<=' not supported between instances of 'str' and 'float'

In [9]:
date_columns = [
    "Rental_Date",
    "Booking_Date",
    "Rental_Start_Date",
    "Expected_Return_Date",
    "Actual_Return_Date",
    "Return_Date",
    "Acquisition_Date",
    "Maintenance_Date",
    "Next_Maintenance_Due"
]

for col in date_columns:
    df[col] = pd.to_datetime(df[col], errors="coerce")

In [10]:
print(df[date_columns].dtypes)

Rental_Date             datetime64[ns]
Booking_Date            datetime64[ns]
Rental_Start_Date       datetime64[ns]
Expected_Return_Date    datetime64[ns]
Actual_Return_Date      datetime64[ns]
Return_Date             datetime64[ns]
Acquisition_Date        datetime64[ns]
Maintenance_Date        datetime64[ns]
Next_Maintenance_Due    datetime64[ns]
dtype: object

In [11]:
for col in date_columns:
    print(f"\n{col}")
    print("Min:", df[col].min())
    print("Max:", df[col].max())

Rental_Date
Min: 2024-01-01 00:00:00
Max: 2026-07-31 00:00:00

Booking_Date
Min: 2023-12-22 00:00:00
Max: 2026-07-30 00:00:00

Rental_Start_Date
Min: 2024-01-01 00:00:00
Max: 2026-07-31 00:00:00

Expected_Return_Date
Min: 2024-01-06 00:00:00
Max: 2026-09-14 00:00:00

Actual_Return_Date
Min: 2024-01-06 00:00:00
Max: 2026-09-14 00:00:00

Return_Date
Min: 2024-01-06 00:00:00
Max: 2026-09-14 00:00:00

Acquisition_Date
Min: 2022-01-03 00:00:00
Max: 2025-07-17 00:00:00

Maintenance_Date
Min: 2022-07-21 00:00:00
Max: 2026-07-26 00:00:00

Next_Maintenance_Due
Min: 2022-12-11 00:00:00
Max: 2027-07-26 00:00:00

In [12]:
# Temporal features

df["Rental_Year"] = df["Rental_Start_Date"].dt.year
df["Rental_Month"] = df["Rental_Start_Date"].dt.month
df["Rental_Quarter"] = df["Rental_Start_Date"].dt.quarter
df["Rental_DayOfWeek"] = df["Rental_Start_Date"].dt.dayofweek
df["Is_Weekend"] = (df["Rental_DayOfWeek"] >= 5).astype(int)

# Booking lead time
df["Booking_Lead_Days"] = (
    df["Rental_Start_Date"] - df["Booking_Date"]
).dt.days

print("New features created successfully.")

New features created successfully.

In [13]:
df[
    [
        "Booking_Date",
        "Rental_Start_Date",
        "Rental_Year",
        "Rental_Month",
        "Rental_Quarter",
        "Rental_DayOfWeek",
        "Is_Weekend",
        "Booking_Lead_Days"
    ]
].head(10)

,Booking_Date,Rental_Start_Date,Rental_Year,Rental_Month,Rental_Quarter,Rental_DayOfWeek,Is_Weekend,Booking_Lead_Days
0,2026-02-06,2026-02-17,2026,2,1,1,0,11
1,2026-07-15,2026-07-18,2026,7,3,5,1,3
2,2026-06-14,2026-06-18,2026,6,2,3,0,4
3,2026-03-23,2026-04-01,2026,4,2,2,0,9
4,2026-06-23,2026-06-26,2026,6,2,4,0,3
5,2026-05-08,2026-05-14,2026,5,2,3,0,6
6,2026-07-12,2026-07-17,2026,7,3,4,0,5
7,2026-04-18,2026-04-25,2026,4,2,5,1,7
8,2026-04-17,2026-05-01,2026,5,2,4,0,14
9,2026-03-07,2026-03-09,2026,3,1,0,0,2

In [14]:
print(df[
    [
        "Rental_Year",
        "Rental_Month",
        "Rental_Quarter",
        "Rental_DayOfWeek",
        "Is_Weekend",
        "Booking_Lead_Days"
    ]
].describe())

       Rental_Year  Rental_Month  Rental_Quarter  Rental_DayOfWeek  \
count  3500.000000   3500.000000     3500.000000       3500.000000
mean   2025.082857      5.609143        2.215143          2.964286
std       0.827847      3.046431        1.010802          1.958744
min    2024.000000      1.000000        1.000000          0.000000
25%    2024.000000      3.000000        1.000000          1.000000
50%    2025.000000      5.000000        2.000000          3.000000
75%    2026.000000      7.000000        3.000000          5.000000
max    2026.000000     12.000000        4.000000          6.000000

        Is_Weekend  Booking_Lead_Days
count  3500.000000        3500.000000
mean      0.267429           6.045429
std       0.442681           3.624477
min       0.000000           1.000000
25%       0.000000           3.000000
50%       0.000000           6.000000
75%       1.000000           9.000000
max       1.000000          14.000000

In [15]:
print("Rental Duration Statistics:")
print(df["Rental_Duration_Days"].describe())

Rental Duration Statistics:
count    3500.000000
mean       12.930286
std        10.511646
min         1.000000
25%         5.000000
50%        10.000000
75%        21.000000
max        60.000000
Name: Rental_Duration_Days, dtype: float64

In [16]:
print("\nUnique rental durations:")
print(sorted(df["Rental_Duration_Days"].unique()))

Unique rental durations:
[np.int64(1), np.int64(3), np.int64(5), np.int64(6), np.int64(7), np.int64(10), np.int64(14), np.int64(20), np.int64(21), np.int64(30), np.int64(42), np.int64(45), np.int64(60)]

In [17]:
print("\nDuration frequency:")
print(df["Rental_Duration_Days"].value_counts().sort_index())

Duration frequency:
Rental_Duration_Days
1     157
3     420
5     471
6       1
7     572
10    415
14    571
20      2
21    368
30    399
42      1
45    122
60      1
Name: count, dtype: int64

In [18]:
df["Rental_Week"] = df["Rental_Start_Date"].dt.isocalendar().week.astype(int)

print("Rental_Week created successfully.")
print(df["Rental_Week"].describe())

Rental_Week created successfully.
count    3500.000000
mean       22.659429
std        13.220123
min         1.000000
25%        12.000000
50%        21.000000
75%        31.000000
max        52.000000
Name: Rental_Week, dtype: float64

In [19]:
df[
    [
        "Rental_Start_Date",
        "Rental_Year",
        "Rental_Week",
        "Rental_Month",
        "Rental_DayOfWeek",
        "Is_Weekend"
    ]
].head(10)

,Rental_Start_Date,Rental_Year,Rental_Week,Rental_Month,Rental_DayOfWeek,Is_Weekend
0,2026-02-17,2026,8,2,1,0
1,2026-07-18,2026,29,7,5,1
2,2026-06-18,2026,25,6,3,0
3,2026-04-01,2026,14,4,2,0
4,2026-06-26,2026,26,6,4,0
5,2026-05-14,2026,20,5,3,0
6,2026-07-17,2026,29,7,4,0
7,2026-04-25,2026,17,4,5,1
8,2026-05-01,2026,18,5,4,0
9,2026-03-09,2026,11,3,0,0

In [20]:
df["Rental_Start_Month_Name"] = df["Rental_Start_Date"].dt.month_name()

print(df["Rental_Start_Month_Name"].value_counts())

Rental_Start_Month_Name
July         440
May          427
March        401
April        398
June         378
February     353
January      258
August       194
December     178
September    171
October      159
November     143
Name: count, dtype: int64

In [21]:
df[
    [
        "Rental_Start_Date",
        "Rental_Month",
        "Rental_Start_Month_Name"
    ]
].head(10)

  Rental_Start_Date  Rental_Month Rental_Start_Month_Name
0        2026-02-17             2                February
1        2026-07-18             7                    July
2        2026-06-18             6                    June
3        2026-04-01             4                   April
4        2026-06-26             6                    June
5        2026-05-14             5                     May
6        2026-07-17             7                    July
7        2026-04-25             4                   April
8        2026-05-01             5                     May
9        2026-03-09             3                   March

In [22]:
monthly_demand = (
    df.groupby(
        [
            df["Rental_Start_Date"].dt.to_period("M"),
            "Equipment"
        ]
    )
    .size()
    .reset_index(name="Rental_Count")
)

monthly_demand.columns = [
    "Rental_Month_Period",
    "Equipment",
    "Rental_Count"
]

print("Shape:", monthly_demand.shape)
monthly_demand.head(20)

Shape: (480, 3)

   Rental_Month_Period            Equipment  Rental_Count
0              2024-01        BiPAP Machine             7
1              2024-01         CPAP Machine             7
2              2024-01        Commode Chair            10
3              2024-01          ECG Machine             3
4              2024-01           Fowler Bed             1
5              2024-01         Hospital Bed             6
6              2024-01        Infusion Pump             1
7              2024-01            Nebulizer             3
8              2024-01  Oxygen Concentrator             8
9              2024-01      Patient Monitor             4
10             2024-01      Suction Machine             3
11             2024-01   Surgical Headlight             1
12             2024-01       Surgical Loupe             1
13             2024-01           Ventilator             1
14             2024-01               Walker             4
15             2024-01           Wheelchair            10
16             2024-02        BiPAP Machine             4
17             2024-02         CPAP Machine            15
18             2024-02        Commode Chair             5
19             2024-02          ECG Machine             4

In [23]:
print("Number of equipment types:", monthly_demand["Equipment"].nunique())
print("\nEquipment types:")
print(monthly_demand["Equipment"].unique())

Number of equipment types: 16

Equipment types:
['BiPAP Machine' 'CPAP Machine' 'Commode Chair' 'ECG Machine' 'Fowler Bed'
 'Hospital Bed' 'Infusion Pump' 'Nebulizer' 'Oxygen Concentrator'
 'Patient Monitor' 'Suction Machine' 'Surgical Headlight' 'Surgical Loupe'
 'Ventilator' 'Walker' 'Wheelchair']

In [24]:
print("\nMonthly demand statistics:")
print(monthly_demand["Rental_Count"].describe())

Monthly demand statistics:
count    480.000000
mean       7.291667
std        5.808562
min        1.000000
25%        3.000000
50%        6.000000
75%        9.000000
max       40.000000
Name: Rental_Count, dtype: float64

In [25]:
# Create a proper datetime column for the monthly demand table

monthly_demand["Month"] = monthly_demand["Rental_Month_Period"].dt.to_timestamp()

# Sort chronologically within each equipment type
monthly_demand = monthly_demand.sort_values(
    ["Equipment", "Month"]
).reset_index(drop=True)

# Previous month's demand for the same equipment
monthly_demand["Historical_Demand_Lag_1"] = (
    monthly_demand.groupby("Equipment")["Rental_Count"].shift(1)
)

print(monthly_demand.head(20))

   Rental_Month_Period      Equipment  Rental_Count      Month  \
0              2024-01  BiPAP Machine             7 2024-01-01
1              2024-02  BiPAP Machine             4 2024-02-01
2              2024-03  BiPAP Machine             2 2024-03-01
3              2024-04  BiPAP Machine            12 2024-04-01
4              2024-05  BiPAP Machine             3 2024-05-01
5              2024-06  BiPAP Machine             4 2024-06-01
6              2024-07  BiPAP Machine             5 2024-07-01
7              2024-08  BiPAP Machine             6 2024-08-01
8              2024-09  BiPAP Machine             5 2024-09-01
9              2024-10  BiPAP Machine             4 2024-10-01
10             2024-11  BiPAP Machine             4 2024-11-01
11             2024-12  BiPAP Machine             5 2024-12-01
12             2025-01  BiPAP Machine             7 2025-01-01
13             2025-02  BiPAP Machine             1 2025-02-01
14             2025-03  BiPAP Machine            11 2025-03-01
15             2025-04  BiPAP Machine             6 2025-04-01
16             2025-05  BiPAP Machine             5 2025-05-01
17             2025-06  BiPAP Machine             6 2025-06-01
18             2025-07  BiPAP Machine             7 2025-07-01
19             2025-08  BiPAP Machine             4 2025-08-01

    Historical_Demand_Lag_1
0                       NaN
1                       7.0
2                       4.0
3                       2.0
4                      12.0
5                       3.0
6                       4.0
7                       5.0
8                       6.0
9                       5.0
10                      4.0
11                      4.0
12                      5.0
13                      7.0
14                      1.0
15                     11.0
16                      6.0
17                      5.0
18                      6.0
19                      7.0

In [26]:
oxygen_demand = monthly_demand[
    monthly_demand["Equipment"] == "Oxygen Concentrator"
][
    [
        "Month",
        "Equipment",
        "Rental_Count",
        "Historical_Demand_Lag_1"
    ]
]

print(oxygen_demand.head(10))

         Month            Equipment  Rental_Count  Historical_Demand_Lag_1
246 2024-01-01  Oxygen Concentrator             8                      NaN
247 2024-02-01  Oxygen Concentrator             9                      8.0
248 2024-03-01  Oxygen Concentrator             5                      9.0
249 2024-04-01  Oxygen Concentrator            12                      5.0
250 2024-05-01  Oxygen Concentrator             9                     12.0
251 2024-06-01  Oxygen Concentrator            14                      9.0
252 2024-07-01  Oxygen Concentrator            10                     14.0
253 2024-08-01  Oxygen Concentrator            11                     10.0
254 2024-09-01  Oxygen Concentrator            10                     11.0
255 2024-10-01  Oxygen Concentrator            11                     10.0

In [27]:
monthly_demand["Historical_Demand_Rolling_3M"] = (
    monthly_demand
    .groupby("Equipment")["Rental_Count"]
    .transform(
        lambda x: x.shift(1).rolling(window=3, min_periods=1).mean()
    )
)

print(monthly_demand.head(10))

  Rental_Month_Period      Equipment  Rental_Count      Month  \
0             2024-01  BiPAP Machine             7 2024-01-01
1             2024-02  BiPAP Machine             4 2024-02-01
2             2024-03  BiPAP Machine             2 2024-03-01
3             2024-04  BiPAP Machine            12 2024-04-01
4             2024-05  BiPAP Machine             3 2024-05-01
5             2024-06  BiPAP Machine             4 2024-06-01
6             2024-07  BiPAP Machine             5 2024-07-01
7             2024-08  BiPAP Machine             6 2024-08-01
8             2024-09  BiPAP Machine             5 2024-09-01
9             2024-10  BiPAP Machine             4 2024-10-01

   Historical_Demand_Lag_1  Historical_Demand_Rolling_3M
0                      NaN                           NaN
1                      7.0                      7.000000
2                      4.0                      5.500000
3                      2.0                      4.333333
4                     12.0                      6.000000
5                      3.0                      5.666667
6                      4.0                      6.333333
7                      5.0                      4.000000
8                      6.0                      5.000000
9                      5.0                      5.333333

In [28]:
oxygen_demand = monthly_demand[
    monthly_demand["Equipment"] == "Oxygen Concentrator"
][
    [
        "Month",
        "Equipment",
        "Rental_Count",
        "Historical_Demand_Lag_1",
        "Historical_Demand_Rolling_3M"
    ]
]

print(oxygen_demand.head(10))

         Month            Equipment  Rental_Count  Historical_Demand_Lag_1  \
246 2024-01-01  Oxygen Concentrator             8                      NaN
247 2024-02-01  Oxygen Concentrator             9                      8.0
248 2024-03-01  Oxygen Concentrator             5                      9.0
249 2024-04-01  Oxygen Concentrator            12                      5.0
250 2024-05-01  Oxygen Concentrator             9                     12.0
251 2024-06-01  Oxygen Concentrator            14                      9.0
252 2024-07-01  Oxygen Concentrator            10                     14.0
253 2024-08-01  Oxygen Concentrator            11                     10.0
254 2024-09-01  Oxygen Concentrator            10                     11.0
255 2024-10-01  Oxygen Concentrator            11                     10.0

     Historical_Demand_Rolling_3M
246                           NaN
247                      8.000000
248                      8.500000
249                      7.333333
250                      8.666667
251                      8.666667
252                     11.666667
253                     11.000000
254                     11.666667
255                     10.333333

In [29]:
monthly_demand["Historical_Demand_Lag_2"] = (
    monthly_demand
    .groupby("Equipment")["Rental_Count"]
    .shift(2)
)

print(
    monthly_demand[
        monthly_demand["Equipment"] == "Oxygen Concentrator"
    ][
        [
            "Month",
            "Rental_Count",
            "Historical_Demand_Lag_1",
            "Historical_Demand_Lag_2"
        ]
    ].head(10)
)

         Month  Rental_Count  Historical_Demand_Lag_1  Historical_Demand_Lag_2
246 2024-01-01             8                      NaN                      NaN
247 2024-02-01             9                      8.0                      NaN
248 2024-03-01             5                      9.0                      8.0
249 2024-04-01            12                      5.0                      9.0
250 2024-05-01             9                     12.0                      5.0
251 2024-06-01            14                      9.0                     12.0
252 2024-07-01            10                     14.0                      9.0
253 2024-08-01            11                     10.0                     14.0
254 2024-09-01            10                     11.0                     10.0
255 2024-10-01            11                     10.0                     11.0

In [30]:
monthly_demand["Historical_Demand_Trend_2M"] = (
    monthly_demand["Historical_Demand_Lag_1"]
    - monthly_demand["Historical_Demand_Lag_2"]
)

print(
    monthly_demand[
        monthly_demand["Equipment"] == "Oxygen Concentrator"
    ][
        [
            "Month",
            "Rental_Count",
            "Historical_Demand_Lag_1",
            "Historical_Demand_Lag_2",
            "Historical_Demand_Trend_2M"
        ]
    ].head(10)
)

         Month  Rental_Count  Historical_Demand_Lag_1  \
246 2024-01-01             8                      NaN
247 2024-02-01             9                      8.0
248 2024-03-01             5                      9.0
249 2024-04-01            12                      5.0
250 2024-05-01             9                     12.0
251 2024-06-01            14                      9.0
252 2024-07-01            10                     14.0
253 2024-08-01            11                     10.0
254 2024-09-01            10                     11.0
255 2024-10-01            11                     10.0

     Historical_Demand_Lag_2  Historical_Demand_Trend_2M
246                      NaN                         NaN
247                      NaN                         NaN
248                      8.0                         1.0
249                      9.0                        -4.0
250                      5.0                         7.0
251                     12.0                        -3.0
252                      9.0                         5.0
253                     14.0                        -4.0
254                     10.0                         1.0
255                     11.0                        -1.0

In [31]:
monthly_demand["Historical_Demand_Rolling_6M"] = (
    monthly_demand
    .groupby("Equipment")["Rental_Count"]
    .transform(
        lambda x: x.shift(1).rolling(window=6, min_periods=1).mean()
    )
)

In [32]:
print(
    monthly_demand[
        monthly_demand["Equipment"] == "Oxygen Concentrator"
    ][
        [
            "Month",
            "Rental_Count",
            "Historical_Demand_Rolling_3M",
            "Historical_Demand_Rolling_6M"
        ]
    ].head(10)
)

         Month  Rental_Count  Historical_Demand_Rolling_3M  \
246 2024-01-01             8                           NaN
247 2024-02-01             9                      8.000000
248 2024-03-01             5                      8.500000
249 2024-04-01            12                      7.333333
250 2024-05-01             9                      8.666667
251 2024-06-01            14                      8.666667
252 2024-07-01            10                     11.666667
253 2024-08-01            11                     11.000000
254 2024-09-01            10                     11.666667
255 2024-10-01            11                     10.333333

     Historical_Demand_Rolling_6M
246                           NaN
247                      8.000000
248                      8.500000
249                      7.333333
250                      8.500000
251                      8.600000
252                      9.500000
253                      9.833333
254                     10.166667
255                     11.000000

In [33]:
equipment_avg_rate = (
    df.groupby("Equipment")["Daily_Rate"]
    .mean()
    .reset_index(name="Average_Rental_Rate")
)

equipment_avg_rate.head()

       Equipment  Average_Rental_Rate
0  BiPAP Machine           534.700000
1   CPAP Machine           359.003322
2  Commode Chair            92.741935
3    ECG Machine           504.213836
4     Fowler Bed           438.561404

In [34]:
print(df["Equipment_Age_Years"].describe())

print("\nMissing values:")
print(df["Equipment_Age_Years"].isna().sum())

print("\nUnique values:")
print(df["Equipment_Age_Years"].nunique())

count    3355.000000
mean        2.800954
std         1.032226
min         1.000000
25%         2.000000
50%         2.800000
75%         3.700000
max         4.600000
Name: Equipment_Age_Years, dtype: float64

Missing values:
145

Unique values:
37

In [35]:
df["Equipment_Availability_Ratio"] = (
    df["Available_Units_At_Start"] / df["Total_Inventory"]
)

print(df["Equipment_Availability_Ratio"].describe())

print("\nMissing values:")
print(df["Equipment_Availability_Ratio"].isna().sum())

count    3500.000000
mean        0.758493
std         0.179642
min         0.150000
25%         0.652174
50%         0.789474
75%         0.894737
max         1.000000
Name: Equipment_Availability_Ratio, dtype: float64

Missing values:
0

In [36]:
df["Equipment_Utilisation_Proxy"] = (
    1 - df["Equipment_Availability_Ratio"]
)

print(df["Equipment_Utilisation_Proxy"].describe())

print("\nMissing values:")
print(df["Equipment_Utilisation_Proxy"].isna().sum())

count    3500.000000
mean        0.241507
std         0.179642
min         0.000000
25%         0.105263
50%         0.210526
75%         0.347826
max         0.850000
Name: Equipment_Utilisation_Proxy, dtype: float64

Missing values:
0

In [38]:
df["Expected_Rental_Revenue"] = (
    df["Rental_Duration_Days"] * df["Daily_Rate"]
)

print(df["Expected_Rental_Revenue"].describe())

print("\nMissing values:")
print(df["Expected_Rental_Revenue"].isna().sum())

count     3500.000000
mean      4149.061429
std       4571.871210
min         70.000000
25%       1197.500000
50%       2520.000000
75%       5200.000000
max      47700.000000
Name: Expected_Rental_Revenue, dtype: float64

Missing values:
0

In [39]:
comparison = pd.DataFrame({
    "Expected_Rental_Revenue": df["Expected_Rental_Revenue"],
    "Total_Rental_Amount": df["Total_Rental_Amount"]
})

comparison["Difference"] = (
    comparison["Total_Rental_Amount"]
    - comparison["Expected_Rental_Revenue"]
)

print(comparison["Difference"].describe())

count    3500.0
mean        0.0
std         0.0
min         0.0
25%         0.0
50%         0.0
75%         0.0
max         0.0
Name: Difference, dtype: float64

In [40]:
df.drop(columns=["Expected_Rental_Revenue"], inplace=True)

print("Expected_Rental_Revenue removed.")
print("Dataset shape:", df.shape)

Expected_Rental_Revenue removed.
Dataset shape: (3500, 45)

In [41]:
print("Total columns:", len(df.columns))

for i, col in enumerate(df.columns, start=1):
    print(i, col)

Total columns: 45
1 Rental_ID
2 Rental_Date
3 Customer_ID
4 Customer_Type
5 Area
6 Equipment
7 Equipment_Category
8 Rental_Duration_Days
9 Daily_Rate
10 Total_Rental_Amount_Original
11 Security_Deposit
12 Delivery_Charge
13 Maintenance_Cost
14 Payment_Mode
15 Rental_Status
16 Equipment_Condition
17 Customer_Rating
18 Return_Date
19 Booking_Date
20 Rental_Start_Date
21 Expected_Return_Date
22 Actual_Return_Date
23 Booking_Status
24 Cancellation_Status
25 Customer_Pincode
26 Equipment_ID
27 Acquisition_Date
28 Maintenance_Date
29 Next_Maintenance_Due
30 Equipment_Age_Years
31 Total_Inventory
32 Available_Units_At_Start
33 Customer_Pincode_Missing
34 Equipment_Info_Missing
35 Total_Rental_Amount
36 Rental_Year
37 Rental_Month
38 Rental_Quarter
39 Rental_DayOfWeek
40 Is_Weekend
41 Booking_Lead_Days
42 Rental_Week
43 Rental_Start_Month_Name
44 Equipment_Availability_Ratio
45 Equipment_Utilisation_Proxy

In [42]:
df["Maintenance_Due"] = (
    df["Rental_Start_Date"] >= df["Next_Maintenance_Due"]
).astype(int)

print(df["Maintenance_Due"].value_counts())
print("\nMissing values:")
print(df["Maintenance_Due"].isna().sum())

Maintenance_Due
0    2038
1    1462
Name: count, dtype: int64

Missing values:
0

In [43]:
df["Maintenance_Days_Remaining"] = (
    df["Next_Maintenance_Due"] - df["Rental_Start_Date"]
).dt.days

print(df["Maintenance_Days_Remaining"].describe())

print("\nMissing values:")
print(df["Maintenance_Days_Remaining"].isna().sum())

count    3255.000000
mean       44.689401
std       476.298459
min     -1318.000000
25%      -269.500000
50%        62.000000
75%       386.000000
max      1256.000000
Name: Maintenance_Days_Remaining, dtype: float64

Missing values:
245

In [44]:
print(
    df.loc[
        df["Maintenance_Days_Remaining"].isna(),
        ["Next_Maintenance_Due", "Maintenance_Date", "Rental_Start_Date"]
    ].head(10)
)

print("\nMissing Next_Maintenance_Due:")
print(df["Next_Maintenance_Due"].isna().sum())

    Next_Maintenance_Due Maintenance_Date Rental_Start_Date
10                   NaT       2025-08-07        2026-03-05
19                   NaT              NaT        2026-05-26
23                   NaT              NaT        2026-07-18
53                   NaT              NaT        2026-03-06
57                   NaT       2023-08-14        2026-06-02
62                   NaT              NaT        2026-02-01
90                   NaT              NaT        2026-06-09
95                   NaT              NaT        2026-03-04
105                  NaT       2026-04-29        2026-02-19
110                  NaT              NaT        2026-06-27

Missing Next_Maintenance_Due:
245

In [45]:
df["Maintenance_Overdue"] = (
    df["Maintenance_Days_Remaining"] < 0
).astype(int)

print(df["Maintenance_Overdue"].value_counts())

Maintenance_Overdue
0    2041
1    1459
Name: count, dtype: int64

In [46]:
print(
    df.loc[
        (df["Maintenance_Due"] == 1) &
        (df["Maintenance_Overdue"] == 0),
        [
            "Rental_Start_Date",
            "Next_Maintenance_Due",
            "Maintenance_Days_Remaining",
            "Maintenance_Due",
            "Maintenance_Overdue"
        ]
    ]
)

     Rental_Start_Date Next_Maintenance_Due  Maintenance_Days_Remaining  \
702         2026-03-27           2026-03-27                         0.0
2350        2024-09-03           2024-09-03                         0.0
2471        2026-01-01           2026-01-01                         0.0

      Maintenance_Due  Maintenance_Overdue
702                 1                    0
2350                1                    0
2471                1                    0

In [47]:
print(
    pd.crosstab(
        df["Maintenance_Due"],
        df["Maintenance_Overdue"]
    )
)

Maintenance_Overdue     0     1
Maintenance_Due
0                    2038     0
1                       3  1459

In [48]:
df.drop(columns=["Maintenance_Due"], inplace=True)

print("Maintenance_Due removed.")
print("Dataset shape:", df.shape)

Maintenance_Due removed.
Dataset shape: (3500, 47)

In [49]:
df["Maintenance_Due_Within_30_Days"] = (
    (df["Maintenance_Days_Remaining"] >= 0) &
    (df["Maintenance_Days_Remaining"] <= 30)
).astype(int)

print(df["Maintenance_Due_Within_30_Days"].value_counts())

Maintenance_Due_Within_30_Days
0    3411
1      89
Name: count, dtype: int64

In [50]:
df["Rental_Extends_Beyond_Maintenance"] = (
    df["Rental_Start_Date"] + pd.to_timedelta(
        df["Rental_Duration_Days"], unit="D"
    ) > df["Next_Maintenance_Due"]
).astype(int)

print(df["Rental_Extends_Beyond_Maintenance"].value_counts())

print("\nMissing values:")
print(df["Rental_Extends_Beyond_Maintenance"].isna().sum())

Rental_Extends_Beyond_Maintenance
0    2002
1    1498
Name: count, dtype: int64

Missing values:
0

In [52]:
df["Rental_Extends_Beyond_Maintenance"] = (
    df["Rental_Start_Date"]
    + pd.to_timedelta(df["Rental_Duration_Days"], unit="D")
    > df["Next_Maintenance_Due"]
).astype("float")

df.loc[
    df["Next_Maintenance_Due"].isna(),
    "Rental_Extends_Beyond_Maintenance"
] = float("nan")

print(
    df["Rental_Extends_Beyond_Maintenance"]
    .value_counts(dropna=False)
)

Rental_Extends_Beyond_Maintenance
0.0    1757
1.0    1498
NaN     245
Name: count, dtype: int64

In [53]:
print("Booking Status:")
print(df["Booking_Status"].value_counts(dropna=False))

print("\nCancellation Status:")
print(df["Cancellation_Status"].value_counts(dropna=False))

print("\nRental Status:")
print(df["Rental_Status"].value_counts(dropna=False))

Booking Status:
Booking_Status
Completed    3009
Confirmed     346
Cancelled     145
Name: count, dtype: int64

Cancellation Status:
Cancellation_Status
Not Cancelled    3355
Cancelled         145
Name: count, dtype: int64

Rental Status:
Rental_Status
Returned     3009
Active        346
Cancelled     145
Name: count, dtype: int64

In [54]:
cancelled = df[df["Booking_Status"] == "Cancelled"]

print("Cancelled bookings:", len(cancelled))

print("\nRental duration:")
print(cancelled["Rental_Duration_Days"].describe())

print("\nEquipment:")
print(cancelled["Equipment"].value_counts().head(10))

print("\nCustomer type:")
print(cancelled["Customer_Type"].value_counts())

Cancelled bookings: 145

Rental duration:
count    145.000000
mean      12.241379
std        9.708441
min        1.000000
25%        5.000000
50%       10.000000
75%       14.000000
max       45.000000
Name: Rental_Duration_Days, dtype: float64

Equipment:
Equipment
Hospital Bed           21
Wheelchair             21
CPAP Machine           15
Suction Machine        13
Oxygen Concentrator    12
Fowler Bed             10
Patient Monitor         9
Commode Chair           8
Nebulizer               7
ECG Machine             5
Name: count, dtype: int64

Customer type:
Customer_Type
Home Care             47
Individual Patient    35
Hospital              32
Clinic                19
Diagnostic Center     12
Name: count, dtype: int64

In [55]:
df["Is_Cancelled"] = (
    df["Booking_Status"] == "Cancelled"
).astype(int)

print(df["Is_Cancelled"].value_counts())

Is_Cancelled
0    3355
1     145
Name: count, dtype: int64

In [56]:
customer_type_duration = (
    df.groupby("Customer_Type")["Rental_Duration_Days"]
    .mean()
    .reset_index(name="Average_Rental_Duration_By_Customer_Type")
)

customer_type_duration

        Customer_Type  Average_Rental_Duration_By_Customer_Type
0              Clinic                                 11.570265
1   Diagnostic Center                                 11.913043
2           Home Care                                 14.309353
3            Hospital                                 11.954167
4  Individual Patient                                 12.954683

In [57]:
customer_type_demand = (
    df.groupby("Customer_Type")
    .size()
    .reset_index(name="Rental_Count")
    .sort_values("Rental_Count", ascending=False)
)

customer_type_demand

        Customer_Type  Rental_Count
2           Home Care          1112
4  Individual Patient           993
3            Hospital           720
0              Clinic           491
1   Diagnostic Center           184

In [58]:
equipment_customer_demand = (
    df.groupby(["Equipment", "Customer_Type"])
    .size()
    .reset_index(name="Rental_Count")
)

print(equipment_customer_demand.head(15))
print("\nRows:", len(equipment_customer_demand))

        Equipment       Customer_Type  Rental_Count
0   BiPAP Machine              Clinic            27
1   BiPAP Machine   Diagnostic Center            10
2   BiPAP Machine           Home Care            62
3   BiPAP Machine            Hospital            36
4   BiPAP Machine  Individual Patient            65
5    CPAP Machine              Clinic            33
6    CPAP Machine   Diagnostic Center            21
7    CPAP Machine           Home Care            86
8    CPAP Machine            Hospital            61
9    CPAP Machine  Individual Patient           100
10  Commode Chair              Clinic            25
11  Commode Chair   Diagnostic Center            12
12  Commode Chair           Home Care            50
13  Commode Chair            Hospital            47
14  Commode Chair  Individual Patient            52

Rows: 79

In [59]:
equipment_category_check = (
    df.groupby("Equipment")["Equipment_Category"]
    .nunique()
)

print(equipment_category_check)

print("\nEquipment types with multiple categories:")
print(
    equipment_category_check[
        equipment_category_check > 1
    ]
)

Equipment
BiPAP Machine          1
CPAP Machine           1
Commode Chair          1
ECG Machine            1
Fowler Bed             1
Hospital Bed           1
Infusion Pump          1
Nebulizer              1
Oxygen Concentrator    1
Patient Monitor        1
Suction Machine        1
Surgical Headlight     1
Surgical Loupe         1
Ventilator             1
Walker                 1
Wheelchair             1
Name: Equipment_Category, dtype: int64

Equipment types with multiple categories:
Series([], Name: Equipment_Category, dtype: int64)

In [60]:
invalid_inventory = df[
    df["Available_Units_At_Start"] > df["Total_Inventory"]
]

print("Invalid inventory records:", len(invalid_inventory))

print("\nAvailable units range:")
print(df["Available_Units_At_Start"].describe())

print("\nTotal inventory range:")
print(df["Total_Inventory"].describe())

Invalid inventory records: 0

Available units range:
count    3500.000000
mean       11.269143
std         4.363010
min         3.000000
25%         8.000000
50%        11.000000
75%        14.000000
max        23.000000
Name: Available_Units_At_Start, dtype: float64

Total inventory range:
count    3500.000000
mean       15.081143
std         4.968002
min         7.000000
25%        11.000000
50%        15.000000
75%        20.000000
max        23.000000
Name: Total_Inventory, dtype: float64

In [61]:
df["Unavailable_Units_At_Start"] = (
    df["Total_Inventory"] - df["Available_Units_At_Start"]
)

print(df["Unavailable_Units_At_Start"].describe())

print("\nMissing values:")
print(df["Unavailable_Units_At_Start"].isna().sum())

count    3500.000000
mean        3.812000
std         3.297496
min         0.000000
25%         1.000000
50%         3.000000
75%         5.000000
max        18.000000
Name: Unavailable_Units_At_Start, dtype: float64

Missing values:
0

In [62]:
print(
    df[
        [
            "Equipment_Availability_Ratio",
            "Equipment_Utilisation_Proxy",
            "Unavailable_Units_At_Start"
        ]
    ].corr()
)

                              Equipment_Availability_Ratio  \
Equipment_Availability_Ratio                      1.000000
Equipment_Utilisation_Proxy                      -1.000000
Unavailable_Units_At_Start                       -0.904403

                              Equipment_Utilisation_Proxy  \
Equipment_Availability_Ratio                    -1.000000
Equipment_Utilisation_Proxy                      1.000000
Unavailable_Units_At_Start                       0.904403

                              Unavailable_Units_At_Start
Equipment_Availability_Ratio                   -0.904403
Equipment_Utilisation_Proxy                     0.904403
Unavailable_Units_At_Start                      1.000000

In [63]:
df.drop(columns=["Equipment_Utilisation_Proxy"], inplace=True)

print("Equipment_Utilisation_Proxy removed.")
print("Dataset shape:", df.shape)

Equipment_Utilisation_Proxy removed.
Dataset shape: (3500, 50)

In [64]:
print("Unique Areas:", df["Area"].nunique())
print("\nAreas:")
print(df["Area"].value_counts())

print("\nUnique Pincodes:", df["Customer_Pincode"].nunique())
print("\nMissing Pincodes:", df["Customer_Pincode"].isna().sum())

Unique Areas: 18

Areas:
Area
Dhankawadi       260
Hinjawadi        235
Koregaon Park    224
Wanowrie         221
Erandwane        219
Shivajinagar     211
Hadapsar         211
Vishrantwadi     209
Viman Nagar      207
Bibwewadi        193
Chinchwad        193
Wakad            177
Kothrud          169
Pimpri           169
Kharadi          164
Aundh            153
Camp             150
Baner            135
Name: count, dtype: int64

Unique Pincodes: 20

Missing Pincodes: 122

In [65]:
area_pincode_check = (
    df.groupby("Area")["Customer_Pincode"]
    .nunique()
)

print(area_pincode_check)

print("\nAreas mapped to multiple pincodes:")
print(
    area_pincode_check[
        area_pincode_check > 1
    ]
)

Area
Aundh            20
Baner            20
Bibwewadi        20
Camp             20
Chinchwad        20
Dhankawadi       20
Erandwane        20
Hadapsar         20
Hinjawadi        20
Kharadi          20
Koregaon Park    20
Kothrud          20
Pimpri           20
Shivajinagar     20
Viman Nagar      20
Vishrantwadi     20
Wakad            20
Wanowrie         20
Name: Customer_Pincode, dtype: int64

Areas mapped to multiple pincodes:
Area
Aundh            20
Baner            20
Bibwewadi        20
Camp             20
Chinchwad        20
Dhankawadi       20
Erandwane        20
Hadapsar         20
Hinjawadi        20
Kharadi          20
Koregaon Park    20
Kothrud          20
Pimpri           20
Shivajinagar     20
Viman Nagar      20
Vishrantwadi     20
Wakad            20
Wanowrie         20
Name: Customer_Pincode, dtype: int64

In [66]:
customer_rental_counts = df["Customer_ID"].value_counts()

print("Unique customers:", df["Customer_ID"].nunique())

print("\nCustomer rental count distribution:")
print(customer_rental_counts.describe())

print("\nCustomers with multiple rentals:")
print((customer_rental_counts > 1).sum())

Unique customers: 579

Customer rental count distribution:
count    579.000000
mean       6.044905
std        3.848523
min        1.000000
25%        3.000000
50%        5.000000
75%        9.000000
max       20.000000
Name: count, dtype: float64

Customers with multiple rentals:
536

In [67]:
df = df.sort_values("Rental_Start_Date").reset_index(drop=True)

df["Customer_Previous_Rentals"] = (
    df.groupby("Customer_ID").cumcount()
)

print(df["Customer_Previous_Rentals"].describe())

print("\nFirst 10 records:")
print(
    df[
        [
            "Customer_ID",
            "Rental_Start_Date",
            "Customer_Previous_Rentals"
        ]
    ].head(10)
)

count    3500.000000
mean        3.745429
std         3.307875
min         0.000000
25%         1.000000
50%         3.000000
75%         6.000000
max        19.000000
Name: Customer_Previous_Rentals, dtype: float64

First 10 records:
  Customer_ID Rental_Start_Date  Customer_Previous_Rentals
0     CUST436        2024-01-01                          0
1     CUST128        2024-01-01                          0
2     CUST418        2024-01-02                          0
3     CUST316        2024-01-02                          0
4     CUST392        2024-01-02                          0
5     CUST135        2024-01-03                          0
6     CUST150        2024-01-03                          0
7     CUST232        2024-01-04                          0
8     CUST469        2024-01-04                          0
9     CUST249        2024-01-05                          0

In [68]:
# Check customers with multiple rentals
repeat_customers = df[
    df["Customer_Previous_Rentals"] > 0
]["Customer_ID"].unique()

print("Customers with previous rentals:", len(repeat_customers))

# Show one customer's history
sample_customer = repeat_customers[0]

print("\nSample customer:", sample_customer)

print(
    df[df["Customer_ID"] == sample_customer][
        [
            "Customer_ID",
            "Rental_Start_Date",
            "Customer_Previous_Rentals"
        ]
    ].sort_values("Rental_Start_Date")
)

Customers with previous rentals: 536

Sample customer: CUST160
     Customer_ID Rental_Start_Date  Customer_Previous_Rentals
20       CUST160        2024-01-10                          0
28       CUST160        2024-01-13                          1
136      CUST160        2024-02-21                          2
523      CUST160        2024-06-26                          3
1067     CUST160        2025-01-01                          4
1080     CUST160        2025-01-06                          5
1178     CUST160        2025-02-06                          6
1336     CUST160        2025-03-30                          7
1605     CUST160        2025-06-26                          8
1739     CUST160        2025-08-06                          9
2035     CUST160        2025-11-27                         10
2187     CUST160        2026-01-14                         11
2410     CUST160        2026-02-27                         12
2853     CUST160        2026-05-01                         13
2927     CUST160        2026-05-11                         14
3092     CUST160        2026-06-04                         15
3139     CUST160        2026-06-10                         16
3240     CUST160        2026-06-26                         17

In [69]:
# Create the month key in the main dataset
df["Rental_Month_Period"] = (
    df["Rental_Start_Date"].dt.to_period("M")
)

# Select only the historical demand features we need
demand_features = monthly_demand[
    [
        "Rental_Month_Period",
        "Equipment",
        "Historical_Demand_Lag_1",
        "Historical_Demand_Lag_2",
        "Historical_Demand_Rolling_3M",
        "Historical_Demand_Rolling_6M",
        "Historical_Demand_Trend_2M"
    ]
]

# Merge historical demand features into the main dataset
df = df.merge(
    demand_features,
    on=["Rental_Month_Period", "Equipment"],
    how="left"
)

print("Dataset shape:", df.shape)

print("\nHistorical demand missing values:")
print(
    df[
        [
            "Historical_Demand_Lag_1",
            "Historical_Demand_Lag_2",
            "Historical_Demand_Rolling_3M",
            "Historical_Demand_Rolling_6M",
            "Historical_Demand_Trend_2M"
        ]
    ].isna().sum()
)

Dataset shape: (3500, 57)

Historical demand missing values:
Historical_Demand_Lag_1          70
Historical_Demand_Lag_2         169
Historical_Demand_Rolling_3M     70
Historical_Demand_Rolling_6M     70
Historical_Demand_Trend_2M      169
dtype: int64

In [70]:
df.drop(columns=["Rental_Month_Period"], inplace=True)

print("Rental_Month_Period removed.")
print("Dataset shape:", df.shape)

Rental_Month_Period removed.
Dataset shape: (3500, 56)

In [71]:
# Check exact duplicate columns
duplicate_columns = []

columns = df.columns

for i in range(len(columns)):
    for j in range(i + 1, len(columns)):
        if df[columns[i]].equals(df[columns[j]]):
            duplicate_columns.append(
                (columns[i], columns[j])
            )

print("Duplicate column pairs:")
for pair in duplicate_columns:
    print(pair)

print("\nNumber of duplicate column pairs:", len(duplicate_columns))

Duplicate column pairs:
('Rental_Date', 'Rental_Start_Date')
('Return_Date', 'Actual_Return_Date')
('Equipment_Info_Missing', 'Is_Cancelled')

Number of duplicate column pairs: 3

In [72]:
print(
    pd.crosstab(
        df["Equipment_Info_Missing"],
        df["Is_Cancelled"]
    )
)

print("\nEquipment_Info_Missing:")
print(df["Equipment_Info_Missing"].value_counts())

print("\nIs_Cancelled:")
print(df["Is_Cancelled"].value_counts())

Is_Cancelled               0    1
Equipment_Info_Missing
0                       3355    0
1                          0  145

Equipment_Info_Missing:
Equipment_Info_Missing
0    3355
1     145
Name: count, dtype: int64

Is_Cancelled:
Is_Cancelled
0    3355
1     145
Name: count, dtype: int64

In [73]:
df.drop(
    columns=[
        "Rental_Date",
        "Return_Date",
        "Equipment_Info_Missing"
    ],
    inplace=True
)

print("Redundant columns removed.")
print("Dataset shape:", df.shape)

Redundant columns removed.
Dataset shape: (3500, 53)

In [74]:
for i, col in enumerate(df.columns, start=1):
    print(i, col)

1 Rental_ID
2 Customer_ID
3 Customer_Type
4 Area
5 Equipment
6 Equipment_Category
7 Rental_Duration_Days
8 Daily_Rate
9 Total_Rental_Amount_Original
10 Security_Deposit
11 Delivery_Charge
12 Maintenance_Cost
13 Payment_Mode
14 Rental_Status
15 Equipment_Condition
16 Customer_Rating
17 Booking_Date
18 Rental_Start_Date
19 Expected_Return_Date
20 Actual_Return_Date
21 Booking_Status
22 Cancellation_Status
23 Customer_Pincode
24 Equipment_ID
25 Acquisition_Date
26 Maintenance_Date
27 Next_Maintenance_Due
28 Equipment_Age_Years
29 Total_Inventory
30 Available_Units_At_Start
31 Customer_Pincode_Missing
32 Total_Rental_Amount
33 Rental_Year
34 Rental_Month
35 Rental_Quarter
36 Rental_DayOfWeek
37 Is_Weekend
38 Booking_Lead_Days
39 Rental_Week
40 Rental_Start_Month_Name
41 Equipment_Availability_Ratio
42 Maintenance_Days_Remaining
43 Maintenance_Overdue
44 Maintenance_Due_Within_30_Days
45 Rental_Extends_Beyond_Maintenance
46 Is_Cancelled
47 Unavailable_Units_At_Start
48 Customer_Previous_Rentals
49 Historical_Demand_Lag_1
50 Historical_Demand_Lag_2
51 Historical_Demand_Rolling_3M
52 Historical_Demand_Rolling_6M
53 Historical_Demand_Trend_2M

In [75]:
print("Columns with missing values:")
print(df.isna().sum()[df.isna().sum() > 0])

Columns with missing values:
Customer_Rating                      246
Expected_Return_Date                 145
Actual_Return_Date                   491
Customer_Pincode                     122
Equipment_ID                         145
Acquisition_Date                     145
Maintenance_Date                     246
Next_Maintenance_Due                 245
Equipment_Age_Years                  145
Maintenance_Days_Remaining           245
Rental_Extends_Beyond_Maintenance    245
Historical_Demand_Lag_1               70
Historical_Demand_Lag_2              169
Historical_Demand_Rolling_3M          70
Historical_Demand_Rolling_6M          70
Historical_Demand_Trend_2M           169
dtype: int64

In [76]:
# Recalculate maintenance flags while preserving missing maintenance information

df["Maintenance_Overdue"] = (
    df["Maintenance_Days_Remaining"] < 0
).astype("float")

df.loc[
    df["Next_Maintenance_Due"].isna(),
    "Maintenance_Overdue"
] = float("nan")


df["Maintenance_Due_Within_30_Days"] = (
    (df["Maintenance_Days_Remaining"] >= 0) &
    (df["Maintenance_Days_Remaining"] <= 30)
).astype("float")

df.loc[
    df["Next_Maintenance_Due"].isna(),
    "Maintenance_Due_Within_30_Days"
] = float("nan")


print("Maintenance flags updated.")
print("\nMissing values:")
print(
    df[
        [
            "Maintenance_Days_Remaining",
            "Maintenance_Overdue",
            "Maintenance_Due_Within_30_Days",
            "Rental_Extends_Beyond_Maintenance"
        ]
    ].isna().sum()
)

print("\nValue counts:")
print("\nMaintenance_Overdue:")
print(df["Maintenance_Overdue"].value_counts(dropna=False))

print("\nMaintenance_Due_Within_30_Days:")
print(df["Maintenance_Due_Within_30_Days"].value_counts(dropna=False))

Maintenance flags updated.

Missing values:
Maintenance_Days_Remaining           245
Maintenance_Overdue                  245
Maintenance_Due_Within_30_Days       245
Rental_Extends_Beyond_Maintenance    245
dtype: int64

Value counts:

Maintenance_Overdue:
Maintenance_Overdue
0.0    1796
1.0    1459
NaN     245
Name: count, dtype: int64

Maintenance_Due_Within_30_Days:
Maintenance_Due_Within_30_Days
0.0    3166
NaN     245
1.0      89
Name: count, dtype: int64

In [77]:
missing_summary = (
    df.isna().sum()
    .loc[lambda x: x > 0]
    .to_frame("Missing_Count")
)

missing_summary["Missing_Percentage"] = (
    missing_summary["Missing_Count"] / len(df) * 100
).round(2)

missing_summary = missing_summary.sort_values(
    "Missing_Percentage",
    ascending=False
)

print(missing_summary)

                                   Missing_Count  Missing_Percentage
Actual_Return_Date                           491               14.03
Customer_Rating                              246                7.03
Maintenance_Date                             246                7.03
Maintenance_Due_Within_30_Days               245                7.00
Next_Maintenance_Due                         245                7.00
Maintenance_Days_Remaining                   245                7.00
Maintenance_Overdue                          245                7.00
Rental_Extends_Beyond_Maintenance            245                7.00
Historical_Demand_Trend_2M                   169                4.83
Historical_Demand_Lag_2                      169                4.83
Expected_Return_Date                         145                4.14
Equipment_Age_Years                          145                4.14
Acquisition_Date                             145                4.14
Equipment_ID                                 145                4.14
Customer_Pincode                             122                3.49
Historical_Demand_Lag_1                       70                2.00
Historical_Demand_Rolling_3M                  70                2.00
Historical_Demand_Rolling_6M                  70                2.00

In [78]:
df.drop(columns=["Customer_Rating"], inplace=True)

print("Customer_Rating removed.")
print("Dataset shape:", df.shape)

Customer_Rating removed.
Dataset shape: (3500, 52)

In [79]:
df.drop(columns=["Actual_Return_Date"], inplace=True)

print("Actual_Return_Date removed.")
print("Dataset shape:", df.shape)

Actual_Return_Date removed.
Dataset shape: (3500, 51)

In [80]:
df.drop(columns=["Expected_Return_Date"], inplace=True)

print("Expected_Return_Date removed.")
print("Dataset shape:", df.shape)

Expected_Return_Date removed.
Dataset shape: (3500, 50)

In [81]:
df.drop(columns=["Equipment_ID"], inplace=True)

print("Equipment_ID removed.")
print("Dataset shape:", df.shape)

Equipment_ID removed.
Dataset shape: (3500, 49)

In [82]:
df.drop(columns=["Acquisition_Date"], inplace=True)

print("Acquisition_Date removed.")
print("Dataset shape:", df.shape)

Acquisition_Date removed.
Dataset shape: (3500, 48)

In [83]:
df.drop(columns=["Maintenance_Date"], inplace=True)

print("Maintenance_Date removed.")
print("Dataset shape:", df.shape)

Maintenance_Date removed.
Dataset shape: (3500, 47)

In [84]:
df.drop(columns=["Next_Maintenance_Due"], inplace=True)

print("Next_Maintenance_Due removed.")
print("Dataset shape:", df.shape)

Next_Maintenance_Due removed.
Dataset shape: (3500, 46)

In [85]:
demand_missing = df[
    df["Historical_Demand_Lag_1"].isna() |
    df["Historical_Demand_Lag_2"].isna()
][
    [
        "Rental_Start_Date",
        "Equipment",
        "Historical_Demand_Lag_1",
        "Historical_Demand_Lag_2",
        "Historical_Demand_Rolling_3M",
        "Historical_Demand_Rolling_6M",
        "Historical_Demand_Trend_2M"
    ]
]

print("Rows with missing historical demand features:", len(demand_missing))
print("\nMonths affected:")
print(
    demand_missing["Rental_Start_Date"]
    .dt.to_period("M")
    .value_counts()
    .sort_index()
)

Rows with missing historical demand features: 169

Months affected:
Rental_Start_Date
2024-01    70
2024-02    93
2024-03     2
2024-04     4
Freq: M, Name: count, dtype: int64

In [86]:
missing_summary = (
    df.isna().sum()
    .loc[lambda x: x > 0]
    .to_frame("Missing_Count")
)

missing_summary["Missing_Percentage"] = (
    missing_summary["Missing_Count"] / len(df) * 100
).round(2)

print(missing_summary.sort_values("Missing_Percentage", ascending=False))

                                   Missing_Count  Missing_Percentage
Maintenance_Days_Remaining                   245                7.00
Maintenance_Due_Within_30_Days               245                7.00
Maintenance_Overdue                          245                7.00
Rental_Extends_Beyond_Maintenance            245                7.00
Historical_Demand_Lag_2                      169                4.83
Historical_Demand_Trend_2M                   169                4.83
Equipment_Age_Years                          145                4.14
Customer_Pincode                             122                3.49
Historical_Demand_Lag_1                       70                2.00
Historical_Demand_Rolling_3M                  70                2.00
Historical_Demand_Rolling_6M                  70                2.00

In [87]:
print(
    "Missing Equipment_Age_Years:",
    df["Equipment_Age_Years"].isna().sum()
)

print(
    "Equipment_Age_Years missing percentage:",
    round(df["Equipment_Age_Years"].isna().mean() * 100, 2),
)

Missing Equipment_Age_Years: 145
Equipment_Age_Years missing percentage: 4.14

In [89]:
print("Total missing values:", df.isna().sum().sum())

print("\nMissing columns:")
print(df.isna().sum()[df.isna().sum() > 0])

Total missing values: 1795

Missing columns:
Customer_Pincode                     122
Equipment_Age_Years                  145
Maintenance_Days_Remaining           245
Maintenance_Overdue                  245
Maintenance_Due_Within_30_Days       245
Rental_Extends_Beyond_Maintenance    245
Historical_Demand_Lag_1               70
Historical_Demand_Lag_2              169
Historical_Demand_Rolling_3M          70
Historical_Demand_Rolling_6M          70
Historical_Demand_Trend_2M           169
dtype: int64

In [90]:
for i, col in enumerate(df.columns, start=1):
    print(i, col)

1 Rental_ID
2 Customer_ID
3 Customer_Type
4 Area
5 Equipment
6 Equipment_Category
7 Rental_Duration_Days
8 Daily_Rate
9 Total_Rental_Amount_Original
10 Security_Deposit
11 Delivery_Charge
12 Maintenance_Cost
13 Payment_Mode
14 Rental_Status
15 Equipment_Condition
16 Booking_Date
17 Rental_Start_Date
18 Booking_Status
19 Cancellation_Status
20 Customer_Pincode
21 Equipment_Age_Years
22 Total_Inventory
23 Available_Units_At_Start
24 Customer_Pincode_Missing
25 Total_Rental_Amount
26 Rental_Year
27 Rental_Month
28 Rental_Quarter
29 Rental_DayOfWeek
30 Is_Weekend
31 Booking_Lead_Days
32 Rental_Week
33 Rental_Start_Month_Name
34 Equipment_Availability_Ratio
35 Maintenance_Days_Remaining
36 Maintenance_Overdue
37 Maintenance_Due_Within_30_Days
38 Rental_Extends_Beyond_Maintenance
39 Is_Cancelled
40 Unavailable_Units_At_Start
41 Customer_Previous_Rentals
42 Historical_Demand_Lag_1
43 Historical_Demand_Lag_2
44 Historical_Demand_Rolling_3M
45 Historical_Demand_Rolling_6M
46 Historical_Demand_Trend_2M

In [91]:
demand_features = [
    "Customer_Type",
    "Area",
    "Equipment",
    "Equipment_Category",
    "Rental_Duration_Days",
    "Daily_Rate",
    "Booking_Lead_Days",
    "Rental_Year",
    "Rental_Month",
    "Rental_Quarter",
    "Rental_DayOfWeek",
    "Is_Weekend",
    "Rental_Week",
    "Equipment_Age_Years",
    "Total_Inventory",
    "Available_Units_At_Start",
    "Customer_Pincode_Missing",
    "Equipment_Availability_Ratio",
    "Unavailable_Units_At_Start",
    "Customer_Previous_Rentals",
    "Historical_Demand_Lag_1",
    "Historical_Demand_Lag_2",
    "Historical_Demand_Rolling_3M",
    "Historical_Demand_Rolling_6M",
    "Historical_Demand_Trend_2M"
]

print("Number of demand features:", len(demand_features))
print("\nDemand Prediction Features:")
for i, feature in enumerate(demand_features, start=1):
    print(i, feature)

Number of demand features: 25

Demand Prediction Features:
1 Customer_Type
2 Area
3 Equipment
4 Equipment_Category
5 Rental_Duration_Days
6 Daily_Rate
7 Booking_Lead_Days
8 Rental_Year
9 Rental_Month
10 Rental_Quarter
11 Rental_DayOfWeek
12 Is_Weekend
13 Rental_Week
14 Equipment_Age_Years
15 Total_Inventory
16 Available_Units_At_Start
17 Customer_Pincode_Missing
18 Equipment_Availability_Ratio
19 Unavailable_Units_At_Start
20 Customer_Previous_Rentals
21 Historical_Demand_Lag_1
22 Historical_Demand_Lag_2
23 Historical_Demand_Rolling_3M
24 Historical_Demand_Rolling_6M
25 Historical_Demand_Trend_2M

In [92]:
print("Number of equipment types:", df["Equipment"].nunique())

print(
    "Number of months:",
    df["Rental_Start_Date"].dt.to_period("M").nunique()
)

print(
    "Expected equipment-month combinations:",
    df["Equipment"].nunique()
    * df["Rental_Start_Date"].dt.to_period("M").nunique()
)

Number of equipment types: 16
Number of months: 31
Expected equipment-month combinations: 496

In [93]:
months = (
    df["Rental_Start_Date"]
    .dt.to_period("M")
    .sort_values()
    .unique()
)

print("Number of months:", len(months))
print("\nMonths:")
for month in months:
    print(month)

Number of months: 31

Months:
2024-01
2024-02
2024-03
2024-04
2024-05
2024-06
2024-07
2024-08
2024-09
2024-10
2024-11
2024-12
2025-01
2025-02
2025-03
2025-04
2025-05
2025-06
2025-07
2025-08
2025-09
2025-10
2025-11
2025-12
2026-01
2026-02
2026-03
2026-04
2026-05
2026-06
2026-07

In [94]:
monthly_demand_final = (
    df.groupby(
        [
            df["Rental_Start_Date"].dt.to_period("M"),
            "Equipment"
        ]
    )
    .size()
    .reset_index(name="Monthly_Demand")
)

monthly_demand_final.columns = [
    "Month",
    "Equipment",
    "Monthly_Demand"
]

monthly_demand_final = monthly_demand_final.sort_values(
    ["Month", "Equipment"]
).reset_index(drop=True)

print("Monthly demand dataset shape:", monthly_demand_final.shape)

print("\nFirst 10 rows:")
print(monthly_demand_final.head(10))

print("\nLast 10 rows:")
print(monthly_demand_final.tail(10))

Monthly demand dataset shape: (480, 3)

First 10 rows:
     Month            Equipment  Monthly_Demand
0  2024-01        BiPAP Machine               7
1  2024-01         CPAP Machine               7
2  2024-01        Commode Chair              10
3  2024-01          ECG Machine               3
4  2024-01           Fowler Bed               1
5  2024-01         Hospital Bed               6
6  2024-01        Infusion Pump               1
7  2024-01            Nebulizer               3
8  2024-01  Oxygen Concentrator               8
9  2024-01      Patient Monitor               4

Last 10 rows:
       Month            Equipment  Monthly_Demand
470  2026-07        Infusion Pump               9
471  2026-07            Nebulizer               8
472  2026-07  Oxygen Concentrator              17
473  2026-07      Patient Monitor              13
474  2026-07      Suction Machine              21
475  2026-07   Surgical Headlight              10
476  2026-07       Surgical Loupe               4
477  2026-07           Ventilator               6
478  2026-07               Walker               6
479  2026-07           Wheelchair              34

In [95]:
all_months = pd.period_range(
    start=df["Rental_Start_Date"].min().to_period("M"),
    end=df["Rental_Start_Date"].max().to_period("M"),
    freq="M"
)

all_equipment = sorted(df["Equipment"].dropna().unique())

complete_grid = pd.MultiIndex.from_product(
    [all_months, all_equipment],
    names=["Month", "Equipment"]
).to_frame(index=False)

missing_combinations = complete_grid.merge(
    monthly_demand_final,
    on=["Month", "Equipment"],
    how="left"
)

missing_combinations = missing_combinations[
    missing_combinations["Monthly_Demand"].isna()
]

print("Expected combinations:", len(complete_grid))
print("Observed combinations:", len(monthly_demand_final))
print("Missing combinations:", len(missing_combinations))

print("\nMissing equipment-month combinations:")
print(missing_combinations.to_string(index=False))

Expected combinations: 496
Observed combinations: 480
Missing combinations: 16

Missing equipment-month combinations:
  Month          Equipment  Monthly_Demand
2024-02      Infusion Pump             NaN
2024-02 Surgical Headlight             NaN
2024-03 Surgical Headlight             NaN
2024-05 Surgical Headlight             NaN
2024-06         Ventilator             NaN
2024-10      Infusion Pump             NaN
2024-10     Surgical Loupe             NaN
2025-03     Surgical Loupe             NaN
2025-03         Ventilator             NaN
2025-05         Ventilator             NaN
2025-06             Walker             NaN
2025-07             Walker             NaN
2025-08     Surgical Loupe             NaN
2025-09             Walker             NaN
2025-10    Suction Machine             NaN
2025-11     Surgical Loupe             NaN

In [96]:
monthly_demand_final = (
    complete_grid.merge(
        monthly_demand_final,
        on=["Month", "Equipment"],
        how="left"
    )
)

monthly_demand_final["Monthly_Demand"] = (
    monthly_demand_final["Monthly_Demand"]
    .fillna(0)
    .astype(int)
)

monthly_demand_final = monthly_demand_final.sort_values(
    ["Month", "Equipment"]
).reset_index(drop=True)

print("Final monthly demand dataset shape:", monthly_demand_final.shape)

print("\nDemand statistics:")
print(monthly_demand_final["Monthly_Demand"].describe())

print("\nNumber of zero-demand equipment-months:")
print((monthly_demand_final["Monthly_Demand"] == 0).sum())

print("\nMissing target values:")
print(monthly_demand_final["Monthly_Demand"].isna().sum())

Final monthly demand dataset shape: (496, 3)

Demand statistics:
count    496.000000
mean       7.056452
std        5.857641
min        0.000000
25%        3.000000
50%        6.000000
75%        9.000000
max       40.000000
Name: Monthly_Demand, dtype: float64

Number of zero-demand equipment-months:
16

Missing target values:
0

In [97]:
monthly_demand_final = monthly_demand_final.sort_values(
    ["Equipment", "Month"]
).reset_index(drop=True)

monthly_demand_final["Historical_Demand_Lag_1"] = (
    monthly_demand_final
    .groupby("Equipment")["Monthly_Demand"]
    .shift(1)
)

monthly_demand_final["Historical_Demand_Lag_2"] = (
    monthly_demand_final
    .groupby("Equipment")["Monthly_Demand"]
    .shift(2)
)

monthly_demand_final["Historical_Demand_Rolling_3M"] = (
    monthly_demand_final
    .groupby("Equipment")["Monthly_Demand"]
    .transform(
        lambda x: x.shift(1).rolling(
            window=3,
            min_periods=1
        ).mean()
    )
)

monthly_demand_final["Historical_Demand_Rolling_6M"] = (
    monthly_demand_final
    .groupby("Equipment")["Monthly_Demand"]
    .transform(
        lambda x: x.shift(1).rolling(
            window=6,
            min_periods=1
        ).mean()
    )
)

monthly_demand_final["Historical_Demand_Trend_2M"] = (
    monthly_demand_final["Historical_Demand_Lag_1"]
    - monthly_demand_final["Historical_Demand_Lag_2"]
)

print("Shape:", monthly_demand_final.shape)

print("\nColumns:")
print(monthly_demand_final.columns.tolist())

print("\nMissing values:")
print(monthly_demand_final.isna().sum())

Shape: (496, 8)

Columns:
['Month', 'Equipment', 'Monthly_Demand', 'Historical_Demand_Lag_1', 'Historical_Demand_Lag_2', 'Historical_Demand_Rolling_3M', 'Historical_Demand_Rolling_6M', 'Historical_Demand_Trend_2M']

Missing values:
Month                            0
Equipment                        0
Monthly_Demand                   0
Historical_Demand_Lag_1         16
Historical_Demand_Lag_2         32
Historical_Demand_Rolling_3M    16
Historical_Demand_Rolling_6M    16
Historical_Demand_Trend_2M      32
dtype: int64

In [98]:
print(
    monthly_demand_final[
        (
            monthly_demand_final["Equipment"] == "Infusion Pump"
        ) &
        (
            monthly_demand_final["Month"].isin(
                [pd.Period("2024-01"), pd.Period("2024-02"), pd.Period("2024-03")]
            )
        )
    ].to_string(index=False)
)

  Month     Equipment  Monthly_Demand  Historical_Demand_Lag_1  Historical_Demand_Lag_2  Historical_Demand_Rolling_3M  Historical_Demand_Rolling_6M  Historical_Demand_Trend_2M
2024-01 Infusion Pump               1                      NaN                      NaN                           NaN                           NaN                         NaN
2024-02 Infusion Pump               0                      1.0                      NaN                           1.0                           1.0                         NaN
2024-03 Infusion Pump               2                      0.0                      1.0                           0.5                           0.5                        -1.0

In [100]:
# Create month name from the month number
monthly_demand_final["Month_Name"] = (
    monthly_demand_final["Month_Number"]
    .map(lambda x: pd.Timestamp(2024, x, 1).month_name())
)

print("Shape:", monthly_demand_final.shape)

print("\nColumns:")
print(monthly_demand_final.columns.tolist())

print("\nSample:")
print(monthly_demand_final.head(10).to_string(index=False))

Shape: (496, 12)

Columns:
['Month', 'Equipment', 'Monthly_Demand', 'Historical_Demand_Lag_1', 'Historical_Demand_Lag_2', 'Historical_Demand_Rolling_3M', 'Historical_Demand_Rolling_6M', 'Historical_Demand_Trend_2M', 'Year', 'Month_Number', 'Quarter', 'Month_Name']

Sample:
  Month     Equipment  Monthly_Demand  Historical_Demand_Lag_1  Historical_Demand_Lag_2  Historical_Demand_Rolling_3M  Historical_Demand_Rolling_6M  Historical_Demand_Trend_2M  Year  Month_Number  Quarter Month_Name
2024-01 BiPAP Machine               7                      NaN                      NaN                           NaN                           NaN                         NaN  2024             1        1    January
2024-02 BiPAP Machine               4                      7.0                      NaN                      7.000000                      7.000000                         NaN  2024             2        1   February
2024-03 BiPAP Machine               2                      4.0                      7.0                      5.500000                      5.500000                        -3.0  2024             3        1      March
2024-04 BiPAP Machine              12                      2.0                      4.0                      4.333333                      4.333333                        -2.0  2024             4        2      April
2024-05 BiPAP Machine               3                     12.0                      2.0                      6.000000                      6.250000                        10.0  2024             5        2        May
2024-06 BiPAP Machine               4                      3.0                     12.0                      5.666667                      5.600000                        -9.0  2024             6        2       June
2024-07 BiPAP Machine               5                      4.0                      3.0                      6.333333                      5.333333                         1.0  2024             7        3       July
2024-08 BiPAP Machine               6                      5.0                      4.0                      4.000000                      5.000000                         1.0  2024             8        3     August
2024-09 BiPAP Machine               5                      6.0                      5.0                      5.000000                      5.333333                         1.0  2024             9        3  September
2024-10 BiPAP Machine               4                      5.0                      6.0                      5.333333                      5.833333                        -1.0  2024            10        4    October

In [101]:
# Create Equipment → Equipment_Category mapping
equipment_category_map = (
    df[["Equipment", "Equipment_Category"]]
    .drop_duplicates()
)

# Verify each equipment has only one category
category_check = (
    equipment_category_map
    .groupby("Equipment")["Equipment_Category"]
    .nunique()
)

print("Equipment types with multiple categories:",
      (category_check > 1).sum())

# Add category to monthly demand dataset
monthly_demand_final = monthly_demand_final.merge(
    equipment_category_map,
    on="Equipment",
    how="left"
)

print("\nShape:", monthly_demand_final.shape)
print("\nMissing Equipment_Category:",
      monthly_demand_final["Equipment_Category"].isna().sum())

print("\nSample:")
print(
    monthly_demand_final[
        ["Month", "Equipment", "Equipment_Category", "Monthly_Demand"]
    ].head(10).to_string(index=False)
)

Equipment types with multiple categories: 0

Shape: (496, 13)

Missing Equipment_Category: 0

Sample:
  Month     Equipment    Equipment_Category  Monthly_Demand
2024-01 BiPAP Machine Respiratory Equipment               7
2024-02 BiPAP Machine Respiratory Equipment               4
2024-03 BiPAP Machine Respiratory Equipment               2
2024-04 BiPAP Machine Respiratory Equipment              12
2024-05 BiPAP Machine Respiratory Equipment               3
2024-06 BiPAP Machine Respiratory Equipment               4
2024-07 BiPAP Machine Respiratory Equipment               5
2024-08 BiPAP Machine Respiratory Equipment               6
2024-09 BiPAP Machine Respiratory Equipment               5
2024-10 BiPAP Machine Respiratory Equipment               4

In [102]:
demand_model_features = [
    "Equipment",
    "Equipment_Category",
    "Year",
    "Month_Number",
    "Quarter",
    "Historical_Demand_Lag_1",
    "Historical_Demand_Lag_2",
    "Historical_Demand_Rolling_3M",
    "Historical_Demand_Rolling_6M",
    "Historical_Demand_Trend_2M"
]

demand_model_df = monthly_demand_final[
    demand_model_features + ["Monthly_Demand"]
].copy()

print("Demand model dataset shape:", demand_model_df.shape)

print("\nColumns:")
print(demand_model_df.columns.tolist())

print("\nMissing values:")
print(demand_model_df.isna().sum())

print("\nDuplicate rows:")
print(demand_model_df.duplicated().sum())

Demand model dataset shape: (496, 11)

Columns:
['Equipment', 'Equipment_Category', 'Year', 'Month_Number', 'Quarter', 'Historical_Demand_Lag_1', 'Historical_Demand_Lag_2', 'Historical_Demand_Rolling_3M', 'Historical_Demand_Rolling_6M', 'Historical_Demand_Trend_2M', 'Monthly_Demand']

Missing values:
Equipment                        0
Equipment_Category               0
Year                             0
Month_Number                     0
Quarter                          0
Historical_Demand_Lag_1         16
Historical_Demand_Lag_2         32
Historical_Demand_Rolling_3M    16
Historical_Demand_Rolling_6M    16
Historical_Demand_Trend_2M      32
Monthly_Demand                   0
dtype: int64

Duplicate rows:
0

In [103]:
print("===== FINAL DEMAND DATASET VALIDATION =====")

print("Shape:", demand_model_df.shape)
print("Duplicate rows:", demand_model_df.duplicated().sum())
print("Missing target values:",
      demand_model_df["Monthly_Demand"].isna().sum())

print("\nEquipment count:",
      demand_model_df["Equipment"].nunique())

print("Equipment categories:",
      demand_model_df["Equipment_Category"].nunique())

print("Year range:",
      demand_model_df["Year"].min(),
      "to",
      demand_model_df["Year"].max())

print("Month range:",
      demand_model_df["Month_Number"].min(),
      "to",
      demand_model_df["Month_Number"].max())

print("\nDemand statistics:")
print(demand_model_df["Monthly_Demand"].describe())

print("\nMissing values:")
print(demand_model_df.isna().sum())

===== FINAL DEMAND DATASET VALIDATION =====
Shape: (496, 11)
Duplicate rows: 0
Missing target values: 0

Equipment count: 16
Equipment categories: 7
Year range: 2024 to 2026
Month range: 1 to 12

Demand statistics:
count    496.000000
mean       7.056452
std        5.857641
min        0.000000
25%        3.000000
50%        6.000000
75%        9.000000
max       40.000000
Name: Monthly_Demand, dtype: float64

Missing values:
Equipment                        0
Equipment_Category               0
Year                             0
Month_Number                     0
Quarter                          0
Historical_Demand_Lag_1         16
Historical_Demand_Lag_2         32
Historical_Demand_Rolling_3M    16
Historical_Demand_Rolling_6M    16
Historical_Demand_Trend_2M      32
Monthly_Demand                   0
dtype: int64

In [104]:
import os

# Create processed-data directory
os.makedirs("data/processed", exist_ok=True)

# Save master feature-engineered dataset
master_file = "data/processed/feature_engineered_medical_equipment_dataset.csv"
df.to_csv(master_file, index=False)

# Save demand prediction dataset
demand_file = "data/processed/demand_prediction_dataset.csv"
demand_model_df.to_csv(demand_file, index=False)

print("Files saved successfully!\n")

print("Master dataset:")
print("File:", master_file)
print("Shape:", df.shape)

print("\nDemand prediction dataset:")
print("File:", demand_file)
print("Shape:", demand_model_df.shape)

Files saved successfully!

Master dataset:
File: data/processed/feature_engineered_medical_equipment_dataset.csv
Shape: (3500, 46)

Demand prediction dataset:
File: data/processed/demand_prediction_dataset.csv
Shape: (496, 11)

In [105]:
import os

print(os.path.exists(
    "data/processed/feature_engineered_medical_equipment_dataset.csv"
))

print(os.path.exists(
    "data/processed/demand_prediction_dataset.csv"
))

True
True

In [106]:
from google.colab import files

files.download(
    "data/processed/feature_engineered_medical_equipment_dataset.csv"
)

files.download(
    "data/processed/demand_prediction_dataset.csv"
)